const messages: Record<string,string> = {
  INVALID_CREDENTIALS: 'The email or password is incorrect.',
  FORBIDDEN: 'You do not have permission to perform that action.',
  NOT_FOUND: 'The requested record was not found.',
  INVALID_SERVICE_MODE: 'Loadgistic currently supports Road Freight loads only.',
  INVALID_TRACKING_MODE: 'Choose Status timeline or Approximate location + status.',
  INVALID_TRACKING_MODE_CHANGE: 'This tracking mode cannot be changed that way.',
  TRACKING_LOCATION_REQUIRED: 'Add a current general area or use the device location before updating this load.',
  TRACKING_NOTE_REQUIRED: 'Add a useful tracking note before publishing this update.',
  INVALID_APPROXIMATE_LOCATION: 'Refresh the approximate device location and try again.',
  DEVICE_LOCATION_DRIVER_ONLY: 'Only the driver with the truck may use device location. Enter a general area manually.',
  TRACKING_ACCESS_DENIED: 'That tracking code is invalid or does not belong to this Business.',
  INVALID_DISTRIBUTION_MODE: 'Choose how this shipment should be shared.',
  INVALID_PRICE_MODE: 'Choose a valid pricing option.',
  FIXED_PRICE_REQUIRED: 'Enter the fixed amount in Ethiopian birr.',
  TARGET_PRICE_REQUIRED: 'Enter the target amount in Ethiopian birr.',
  MISSING_REQUIRED_FIELDS: 'Complete the required fields.',
  PROVIDER_REQUIRED: 'Choose a provider for a direct request.',
  INVALID_PROVIDER: 'The selected provider is invalid.',
  INVALID_STATUS_TRANSITION: 'That status change is not allowed from the current status.',
  NOTE_REQUIRED: 'Enter a note before saving.',
  INVALID_VEHICLE: 'Choose one of your active vehicles.',
  CAPACITY_CONFIGURATION_REQUIRED: 'A fleet owner must configure this truck before it can return On Duty.',
  INVALID_CAPACITY_STATUS: 'Choose Empty, Partial, or Off Duty.',
  CAPACITY_PERCENT_REQUIRED: 'Enter a whole percentage from 1 to 99 for partial capacity.',
  ACCEPTED_LOADS_REQUIRED: 'Choose FTL, PTL, or Both.',
  CAPACITY_AREA_REQUIRED: 'Enter the general area where the truck is now.',
  INVALID_CAPACITY_VISIBILITY: 'Choose Public or Partners.',
  FREIGHT_LOAD_TYPE_REQUIRED: 'Choose FTL or PTL for this freight load.',
  RECEIVER_CONTACT_REQUIRED: 'Add the receiver first name and phone before assigning this shipment.',
  RECEIVER_CONTACT_NOT_READY: 'Receiver contact can be added after the shipment is agreed.',
  LOAD_PROOF_ALREADY_REQUESTED: 'Load proof has already been requested.',
  INVALID_INTEREST: 'Choose an interested transporter for this proof.',
  ROUTE_LOCATIONS_MUST_DIFFER: 'Origin and destination branches must be different.',
  INVALID_PROOF_TYPE: 'Choose a valid proof type.',
  FILE_REQUIRED: 'Choose a file to upload.',
  FILE_TOO_LARGE: 'The file is larger than the allowed limit.',
  UNSUPPORTED_FILE_TYPE: 'Upload a JPG, PNG, WebP, or PDF file.',
  NOT_DIRECT_REQUEST: 'Only a direct request can be accepted from this action.',
  DIRECT_REQUEST_NOT_PENDING: 'This direct request has already been handled.',
  INVALID_STATUS: 'Choose a valid review status.',
  APPLICATION_ALREADY_REVIEWED: 'This application already has a final review outcome.',
  PAYMENT_PROOF_ALREADY_REVIEWED: 'This payment proof already has a final review outcome.',
  INVALID_VERIFICATION_TYPE: 'Choose a verification type that matches this profile or truck.',
  VERIFICATION_DOCUMENT_REQUIRED: 'Enter the document name and attach the verification document.',
  VERIFICATION_ALREADY_SUBMITTED: 'This verification already has a pending or approved request.',
  VERIFICATION_ALREADY_REVIEWED: 'This verification request already has a final decision.',
  REVIEW_NOT_ALLOWED: 'Business reviews are available only between the shipper and receiver after a completed load.',
  INVALID_RATING: 'Choose a rating from one to five.',
  REVIEW_ALREADY_SUBMITTED: 'This Business has already reviewed the other participant for this load.',
  PASSWORD_TOO_SHORT: 'Use a password with at least 10 characters.',
  EMAIL_ALREADY_EXISTS: 'An account already exists for that email.',
  INVALID_APPLICATION_TYPE: 'Choose a valid business or provider type.',
  SUBSCRIPTION_NOT_FOUND: 'No subscription is assigned to this workspace yet.',
  INVALID_NETWORK_TARGET: 'Choose an eligible Business or transport provider.',
  INVALID_NETWORK_ACTION: 'Choose a valid network action.',
  NETWORK_RELATIONSHIP_NOT_FOUND: 'That network relationship was not found.',
  NETWORK_REQUEST_NOT_ACTIONABLE: 'That network request is no longer available.'
};

export function errorMessage(error: unknown) {
  const code = error instanceof Error ? error.message : 'UNKNOWN_ERROR';
  return messages[code] || 'Something went wrong. Please try again.';
}
