const messages: Record<string,string> = {
  INVALID_CREDENTIALS: 'The email or password is incorrect.',
  FORBIDDEN: 'You do not have permission to perform that action.',
  NOT_FOUND: 'The requested record was not found.',
  INVALID_SERVICE_MODE: 'Loadgistic currently supports Road Freight shipments only.',
  INVALID_TRACKING_MODE: 'Choose Status timeline or Approximate location + status.',
  INVALID_TRACKING_MODE_CHANGE: 'This tracking mode cannot be changed that way.',
  TRACKING_LOCATION_REQUIRED: 'Add a current general area or use the device location before updating this shipment.',
  TRACKING_LOCATION_NOT_ENABLED: 'This shipment uses status updates. Choose the current shipment status instead.',
  INVALID_APPROXIMATE_LOCATION: 'Refresh the approximate device location and try again.',
  DEVICE_LOCATION_DRIVER_ONLY: 'Only the driver with the truck may use device location. Enter a general area manually.',
  TRACKING_ACCESS_DENIED: 'That tracking code is invalid or does not belong to this Business.',
  INVALID_DISTRIBUTION_MODE: 'Choose how this shipment should be shared.',
  INVALID_MOVEMENT_SCOPE: 'Choose Local or Long-distance routes.',
  LOCALITY_REQUIRED: 'Choose an Ethiopian city, town, or local area from the search results.',
  INVALID_LOCALITY: 'Choose a valid Ethiopian place from the search results.',
  INVALID_SERVICE_RADIUS: 'Choose an operating radius from 5 to 100 km.',
  INVALID_ETHIOPIA_POINT: 'Place pickup and drop-off pins within Ethiopia.',
  INVALID_PRICE_MODE: 'Choose a valid pricing option.',
  FIXED_PRICE_REQUIRED: 'Enter the fixed amount in Ethiopian birr.',
  TARGET_PRICE_REQUIRED: 'Enter the target amount in Ethiopian birr.',
  MISSING_REQUIRED_FIELDS: 'Complete the required fields.',
  PROVIDER_REQUIRED: 'Choose a provider for a direct request.',
  INVALID_PROVIDER: 'The selected provider is invalid.',
  BUSINESS_PARTY_REQUIRED: 'Choose the other Business from the search results.',
  EXTERNAL_PARTY_REQUIRED: 'Enter the external shipper or receiver name.',
  INVALID_BUSINESS_PARTY: 'The selected Business is invalid.',
  INVALID_ETB_AMOUNT: 'Enter a valid amount in Ethiopian birr.',
  INVALID_STATUS_TRANSITION: 'That status change is not allowed from the current status.',
  NOTE_REQUIRED: 'Enter a note before saving.',
  INVALID_VEHICLE: 'Choose one of your active vehicles.',
  SHIPMENT_VEHICLE_REQUIRED: 'Choose a truck with an assigned driver before starting this shipment.',
  CAPACITY_CONFIGURATION_REQUIRED: 'A fleet owner must configure this truck before it can return On Duty.',
  INVALID_CAPACITY_STATUS: 'Choose Empty, Partial, Busy, or Off Duty.',
  CAPACITY_PERCENT_REQUIRED: 'Enter a whole percentage from 1 to 99 for partial capacity.',
  LOCAL_CAPACITY_MUST_BE_EMPTY: 'Local-only capacity must be Empty with 100% of the truck available. Use Long-distance routes or Both for Partial capacity.',
  ACCEPTED_LOADS_REQUIRED: 'Choose Full Truckload, Partial Truckload, or Both.',
  CAPACITY_AREA_REQUIRED: 'Enter the general area where the truck is now.',
  BUSY_AVAILABLE_DATE_REQUIRED: 'Choose when the truck will be available again.',
  INVALID_BUSY_AVAILABLE_DATE: 'The available-again date cannot be in the past.',
  INVALID_CAPACITY_VISIBILITY: 'Choose Public or Partners.',
  PLANNED_ROUTE_DATE_REQUIRED: 'Choose the planned travel date.',
  INVALID_ROUTE_DATE: 'Route dates cannot be in the past.',
  PLANNED_SPACE_STATUS_REQUIRED: 'Choose Full or Partial cargo space for the planned route.',
  ROUTE_ENDPOINTS_REQUIRED: 'Complete both cities for the route, or leave both blank.',
  FREIGHT_LOAD_TYPE_REQUIRED: 'Choose Full Truckload or Partial Truckload for this freight shipment.',
  RECEIVER_CONTACT_REQUIRED: 'Add the receiver first name and phone before assigning this shipment.',
  RECEIVER_CONTACT_NOT_READY: 'Receiver contact can be added after the shipment is agreed.',
  LOAD_PROOF_ALREADY_REQUESTED: 'Shipment proof has already been requested.',
  INVALID_INTEREST: 'Choose an interested transporter for this proof.',
  ROUTE_LOCATIONS_MUST_DIFFER: 'Origin and destination branches must be different.',
  INVALID_PROOF_TYPE: 'Choose a valid proof type.',
  FILE_REQUIRED: 'Choose a file to upload.',
  FILE_TOO_LARGE: 'The file is larger than the allowed limit.',
  UNSUPPORTED_FILE_TYPE: 'Upload a JPG, PNG, WebP, or PDF file.',
  FILE_CONTENT_MISMATCH: 'The file contents do not match the selected file type.',
  PRIVATE_STORAGE_WRITE_FAILED: 'The private file could not be stored. Try again.',
  PRIVATE_STORAGE_READ_FAILED: 'The private file is temporarily unavailable.',
  NOT_DIRECT_REQUEST: 'Only a direct request can be accepted from this action.',
  DIRECT_REQUEST_NOT_PENDING: 'This direct request has already been handled.',
  INVALID_STATUS: 'Choose a valid review status.',
  APPLICATION_ALREADY_REVIEWED: 'This application already has a final review outcome.',
  PAYMENT_PROOF_ALREADY_REVIEWED: 'This payment proof already has a final review outcome.',
  INVALID_VERIFICATION_TYPE: 'Choose a verification type that matches this profile or truck.',
  VERIFICATION_DOCUMENT_REQUIRED: 'Enter the document name and attach the verification document.',
  VERIFICATION_ALREADY_SUBMITTED: 'This verification already has a pending or approved request.',
  VERIFICATION_ALREADY_REVIEWED: 'This verification request already has a final decision.',
  REVIEW_NOT_ALLOWED: 'Business reviews are available only between the shipper and receiver after a completed shipment.',
  INVALID_RATING: 'Choose a rating from one to five.',
  LOW_RATING_NOTE_REQUIRED: 'Add a note explaining a one-, two-, or three-star rating for administrator review.',
  REVIEW_ALREADY_SUBMITTED: 'This Business has already reviewed the other participant for this shipment.',
  INVALID_RATING_REVIEW_STATUS: 'Choose Publish or Dismiss for this rating.',
  RATING_REVIEW_NOTE_REQUIRED: 'Record an investigation note before completing this rating review.',
  RATING_ALREADY_REVIEWED: 'This rating already has a final review outcome.',
  PASSWORD_TOO_SHORT: 'Use a password with at least 10 characters.',
  EMAIL_ALREADY_EXISTS: 'An account already exists for that email.',
  INVALID_APPLICATION_TYPE: 'Choose a valid business or provider type.',
  SUBSCRIPTION_NOT_FOUND: 'No subscription is assigned to this workspace yet.',
  SUBSCRIPTION_ACCESS_REQUIRED: 'Your trial or paid access has expired. Open Plan & billing to restore access.',
  SPONSORED_ACCESS_BUSINESS_ONLY: 'Sponsored free access is available only to approved Businesses.',
  PAYMENT_NOT_REQUIRED: 'This sponsored Business does not need to submit payment.',
  INVALID_NETWORK_TARGET: 'Choose an eligible Business or transport provider.',
  INVALID_NETWORK_ACTION: 'Choose a valid network action.',
  NETWORK_RELATIONSHIP_NOT_FOUND: 'That network relationship was not found.',
  NETWORK_REQUEST_NOT_ACTIONABLE: 'That network request is no longer available.',
  ADMIN_SELF_SUSPENSION_DENIED: 'An administrator cannot suspend their own account.',
  INVALID_ADMIN_RECORD_TYPE: 'Choose a supported account or truck record.',
  INVALID_ADMIN_OPERATIONS_VIEW: 'Choose a supported platform record view.',
  INVALID_SUPPORT_CATEGORY: 'Choose what you need help with.',
  SUPPORT_MESSAGE_REQUIRED: 'Enter a message before sending.',
  SUPPORT_MESSAGE_TOO_LONG: 'Keep the support message under 2,000 characters.',
  SUPPORT_MESSAGE_RATE_LIMITED: 'Too many messages were sent. Wait a minute and try again.',
  SUPPORT_CONVERSATION_ALREADY_OPEN: 'Your current support conversation is already open.',
  SUPPORT_CONVERSATION_CLOSED: 'This support conversation is closed.',
  SUPPORT_CONVERSATION_NOT_WAITING: 'That conversation has already been assigned.',
  SUPPORT_AGENT_UNAVAILABLE: 'Set yourself available before taking another conversation.',
  SUPPORT_AGENT_AT_CAPACITY: 'Close an assigned conversation before taking another.',
  INVALID_SUPPORT_AGENT_LIMIT: 'Choose an agent limit from 1 to 20 open conversations.',
  INVALID_SUPPORT_VIEW: 'Choose Assigned, Waiting, or Closed support conversations.'
};

export function errorMessage(error: unknown) {
  const code = error instanceof Error ? error.message : 'UNKNOWN_ERROR';
  return messages[code] || 'Something went wrong. Please try again.';
}
