// Shared policy copy only. No user data, provider clients or credentials.
export const privacyContact='marketvision.tech@gmail.com';
export const privacySections=[
 ['Information we use','Loadgistic uses account names, emails and phone numbers; profile and truck details; capacity and shipment updates; messages; and files you choose to upload. We use these to run the service, verify access, review documents and handle safety or support issues.'],
 ['Public and private information','You choose the business details and capacity signals to publish or share privately. Login information and uploaded proof or identity files stay private. Authorized shipment parties can see the tracking information and proofs shared with them.'],
 ['Location during shipments',"Loadgistic collects your phone's location to update your active shipment, even when the app is closed or not in use."],
 ['Location controls','For automatic shipment updates, location is obscured on the phone before it is sent. The chosen radius is at most 20 km. Updates end when unloading is approved or tracking ends. You can deny or revoke permission in phone settings; battery settings or stopping the app can interrupt updates.'],
 ['Service providers','Supabase stores account and application data and private files. Our hosting and email services deliver the website and verification messages. Map tile providers receive the map areas requested and network information such as an IP address. Expo and Firebase Cloud Messaging deliver optional phone alerts.'],
 ['Phone notifications','If you enable alerts, we register a device token and installation identifier for chat and Tracking updates. Alerts contain no message text, names, contacts, routes or proof files. You can turn alerts off in Updates or phone settings.'],
 ['Access and retention','Tracking email sessions last five minutes; private-capacity sessions expire after 30 minutes without activity. Shipment-party access ends 30 days after completion. Account information remains while your account is used. Security and shipment event records may be retained to handle abuse, disputes or outstanding obligations.'],
 ['Delete account and data','Request permanent deletion from Account security in the app or the deletion page on our website. We verify your email and review requests within 30 days. An unfinished shipment, company transfer or shared record may need to be resolved first; the request status explains any delay.'],
 ['What deletion removes','Deletion removes your account login and contact details, public profile, personal documents and account-linked messages. Essential shipment and security event records can remain without your account contact details. Deactivation only pauses access and retains history; it is a separate choice.'],
 ['Your choices','You can edit your details, choose what to share, decline optional permissions, block a transporter or report content. Do not upload information you do not have permission to share. Contact us about privacy, correction or deletion using the email below.'],
];
