import { requireUser } from '@/lib/auth';
import { listApplications, listAudit } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { Flash } from '@/components/flash';
import { StatusPill } from '@/components/status-pill';

const accountTypeLabels:Record<string,string>={ENTERPRISE_SHIPPER:'Business',ENTERPRISE_RECEIVER:'Business',TRANSPORT_COMPANY:'Fleet transporter',INDEPENDENT_PROVIDER:'Self-managed driver / owner-operator'};

export default async function ApplicationsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){const user=await requireUser(['ADMIN']);const query=await searchParams;const apps:any[]=listApplications(user);const audit:any[]=listAudit(user);return <div className="page"><PageHeader title="Workspace applications" subtitle="Review businesses looking for capacity and transporters looking for demand."/><Flash error={query.error} success={query.success}/><div className="two-col"><section className="stack">{apps.map(app=><article className="card" key={app.id}><div style={{display:'flex',justifyContent:'space-between',gap:12}}><div><h3>{app.business_name}</h3><div className="meta">{accountTypeLabels[app.application_type]||app.application_type} · {app.email}</div></div><StatusPill status={app.status}/></div><p>{app.notes}</p><form action={`/api/admin/applications/${app.id}`} method="post" className="form-grid"><div className="form-group"><label htmlFor={`decision-${app.id}`}>Decision</label><select id={`decision-${app.id}`} name="status" defaultValue="APPROVED"><option value="APPROVED">Approve</option><option value="MORE_INFO">Request more information</option><option value="REJECTED">Reject</option></select></div><div className="form-group"><label htmlFor={`review-note-${app.id}`}>Review note</label><input id={`review-note-${app.id}`} name="notes" placeholder="Reason or next step"/></div><button className="button" type="submit">Save decision</button></form></article>)}</section><aside className="card"><h3>Recent audit activity</h3>{audit.length?<div className="stack">{audit.slice(0,12).map(row=><div key={row.id}><strong>{row.action.replaceAll('_',' ')}</strong><div className="meta">{row.actor_name||'System'} · {row.entity_type} · {new Date(row.created_at).toLocaleString()}</div></div>)}</div>:<p className="muted">Review activity will appear here.</p>}</aside></div></div>}
