import { requireUser } from '@/lib/auth';
import { listRoutesAndCenters } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { Flash } from '@/components/flash';
import { StatusPill } from '@/components/status-pill';

export default async function RoutesCentersPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(['PARCEL','ADMIN']); const query=await searchParams; const data:any=listRoutesAndCenters(user);
 return <div className="page"><PageHeader title="Routes & centers" subtitle="Show business customers where they can drop off, receive, transfer, or request direct delivery."/><Flash error={query.error} success={query.success}/><div className="two-col"><div className="stack"><section className="card"><h2 style={{fontSize:'1.4rem'}}>Centers</h2><div className="stack">{data.locations.map((l:any)=><article className="card" key={l.id}><div style={{display:'flex',justifyContent:'space-between'}}><div><h3>{l.name}</h3><div className="meta">{l.city} · {l.details}</div></div><StatusPill status={l.active?'Approved':'Expired'}/></div><p>{l.phone} · {l.business_hours}</p><div style={{display:'flex',gap:7,flexWrap:'wrap'}}>{l.accepts_dropoff?<span className="status">Drop-off</span>:null}{l.receiver_pickup?<span className="status green">Receiver pickup</span>:null}{l.supports_transfer?<span className="status purple">Transfer</span>:null}{l.direct_delivery?<span className="status orange">Direct delivery</span>:null}</div></article>)}</div></section><section className="card"><h2 style={{fontSize:'1.4rem'}}>Public routes</h2><div className="stack">{data.routes.map((r:any)=><article className="card" key={r.id}><h3>{r.origin_name} ({r.origin_city}) → {r.destination_name} ({r.destination_city})</h3><div className="meta">{r.service_days||'Days arranged directly'} · {r.estimated_time||'Time confirmed directly'}</div><div style={{display:'flex',gap:7,flexWrap:'wrap',marginTop:10}}>{r.branch_dropoff?<span className="status">Branch drop-off</span>:null}{r.receiver_pickup?<span className="status green">Receiver pickup</span>:null}{r.direct_delivery?<span className="status purple">Direct delivery</span>:null}</div></article>)}</div></section></div>
 <aside className="stack"><section className="form-card"><h3>Add center</h3><form action="/api/locations" method="post" className="stack"><input name="name" required placeholder="Center name"/><input name="city" required placeholder="City or area"/><input name="details" placeholder="Landmark or description"/><input name="phone" placeholder="Business phone"/><input name="businessHours" placeholder="Mon-Sat 8:00-18:00"/><div className="checkbox-row"><label><input type="checkbox" name="acceptsDropoff"/>Drop-off</label><label><input type="checkbox" name="receiverPickup"/>Receiver pickup</label><label><input type="checkbox" name="supportsTransfer"/>Transfer</label><label><input type="checkbox" name="directDelivery"/>Direct delivery</label></div><button className="button">Add center</button></form></section><section className="form-card"><h3>Add route</h3><form action="/api/routes" method="post" className="stack"><select name="originLocationId" required><option value="">Origin center</option>{data.locations.map((l:any)=><option key={l.id} value={l.id}>{l.name} — {l.city}</option>)}</select><select name="destinationLocationId" required><option value="">Destination center</option>{data.locations.map((l:any)=><option key={l.id} value={l.id}>{l.name} — {l.city}</option>)}</select><input name="serviceDays" placeholder="Service days (optional)"/><input name="estimatedTime" placeholder="Estimated movement time"/><div className="checkbox-row"><label><input type="checkbox" name="branchDropoff"/>Branch drop-off</label><label><input type="checkbox" name="receiverPickup"/>Receiver pickup</label><label><input type="checkbox" name="directDelivery"/>Direct delivery</label><label><input type="checkbox" name="publicVisibility" defaultChecked/>Public</label></div><button className="button">Add route</button></form></section></aside></div></div>;
}
