import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { listDirectoryProfiles } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { Flash } from '@/components/flash';
import { StatusPill } from '@/components/status-pill';
import { VerificationBadges } from '@/components/verification-badges';
import { Building2, MapPin, Star, Truck, UserRound, Users } from 'lucide-react';

export default async function ProvidersPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); const query=await searchParams; const type=query.type||'ALL'; const profiles:any[]=listDirectoryProfiles(type);
 return <div className="page"><PageHeader title="Business and Transporter Directory" subtitle="Confirm Businesses, fleet transporters, self-managed drivers, and verified trucks."/><Flash error={query.error} success={query.success}/><div className="directory-filters">{[['ALL','All',Users],['BUSINESS','Businesses',Building2],['TRANSPORT','Fleet Transporters',Truck],['DRIVER','Self-managed Drivers',UserRound]].map(([v,l,Icon]:any)=><Link className={`button ${type===v?'':'secondary'} icon-button-label`} href={`/app/providers?type=${v}`} key={v}><Icon aria-hidden="true"/>{l}</Link>)}</div><div className="grid-3">{profiles.map((p:any)=><article className="card directory-card" key={`${p.ref_kind}-${p.id}`}><div className="directory-card-top"><span className="status">{p.is_business?'BUSINESS':p.type.replaceAll('_',' ')}</span>{p.verified?<StatusPill status="Approved"/>:null}</div><div className="directory-identity"><div className="company-logo small">{p.name.split(' ').slice(0,2).map((word:string)=>word[0]).join('')}</div><div><h3>{p.name}</h3><div className="meta icon-meta"><MapPin aria-hidden="true"/>{p.city||'Location not added'}</div></div></div><VerificationBadges badges={p.verification_badges} compact/><p className="muted">{p.about||p.headline||'Profile information is being completed.'}</p>{p.is_business?<div className="provider-facts"><div><span><Star aria-hidden="true"/>Rating</span><strong>{p.review_count?`${p.average_rating} / 5`:'New'}</strong></div><div><span>Completed reviews</span><strong>{p.review_count||0}</strong></div></div>:<><p><strong>Preferred corridors:</strong><br/>{p.corridors||'Contact transporter'}</p><div className="provider-facts"><div><span>Registered trucks</span><strong>{p.fleet_size}</strong></div><div><span>On Capacity Board</span><strong>{p.active_capacity_count}</strong></div></div></>}<div className="hero-actions"><Link href={`/companies/${p.handle}`} className="button secondary">View Profile</Link>{p.is_business&&['SHIPPER','RECEIVER'].includes(user.role)&&p.id!==user.organization_id?<Link href={`/app/shipments/new?receiver=${p.id}`} className="button">Create load</Link>:!p.is_business&&['SHIPPER','RECEIVER'].includes(user.role)?<Link href={`/app/shipments/new?provider=${p.ref_kind}:${p.id}`} className="button">Send request</Link>:null}</div></article>)}</div></div>;
}
