
import {Text} from '@/components/localization';
import type { Metadata } from 'next';
import Link from 'next/link';
import { ArrowRight, Boxes, Factory, Gauge, ShieldCheck, Truck } from 'lucide-react';
import { PublicHeader } from '@/components/public-header';

export const metadata:Metadata={title:'About',description:'How transporters share capacity with brokers and businesses, keep shipment partners informed, and build confidence through document review.'};

export default function AboutPage(){return <><PublicHeader/><main className="public-app-page public-information-workspace"><header className="public-information-heading container"><span><Factory aria-hidden="true"/><Text message="About Loadgistic"/></span><h1><Text message="Share capacity. Keep customers informed."/></h1><p><Text message="Capacity sharing and professional shipment tracking for Ethiopia's transporters and the businesses they serve."/></p></header><div className="container public-information-grid about-information-grid"><section><Truck aria-hidden="true"/><h2><Text message="Share available capacity"/></h2><p><Text message="Share truck availability with the brokers and businesses you know, or publish it to the open market."/></p></section><section><Gauge aria-hidden="true"/><h2><Text message="Connect with transporters"/></h2><p><Text message="Find a truck for your route and agree on the work directly with its transporter."/></p></section><section><Boxes aria-hidden="true"/><h2><Text message="Keep shipment partners informed"/></h2><p><Text message="Transporters provide private tracking updates to brokers and their customers, or directly to businesses shipping or receiving goods."/></p></section><section><ShieldCheck aria-hidden="true"/><h2><Text message="Build confidence"/></h2><p><Text message="Optional document review helps customers assess the transporter, driver and truck behind a capacity signal."/></p></section></div><aside className="container public-information-note about-information-actions"><ShieldCheck aria-hidden="true"/><span><strong><Text message="Choose your next step"/></strong><Text message="Find open capacity, view capacity shared with you, or publish your trucks."/></span><div><Link className="button" href="/"><Truck aria-hidden="true"/><Text message="Find capacity"/></Link><Link className="button secondary" href="/apply"><ArrowRight aria-hidden="true"/><Text message="Join as a transporter"/></Link></div></aside></main></>}
