import {createContext,useCallback,useContext,useEffect,useMemo,useRef,useState,type PropsWithChildren} from 'react';
import {AppState,Modal,Platform,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {router,type Href} from 'expo-router';
import {useAccount} from './provider';
import * as Storage from './storage';
import {brokerageStorageKey,watchBrokerageAccess} from './brokerage-alert-access';
import {parseSavedChat} from './brokerage-controller';
import {apiRequest} from '../api/http';
import {isChatMessageVisible,blockChatReading} from './chat-visibility';
import {chatAlertSnapshot} from '../../../../src/lib/chat-read-policy.js';
import {chatAlertCopy,createChatAlertTracker} from '../../../../src/lib/chat-alert-delivery.js';
import type {ChatAlertSnapshot,ChatAlertEvent,ChatAlertItem} from '../../../../src/lib/chat-alert-contract';
import {useLanguage} from '../localization/provider';
import {AppIcon} from '../components/app-icon';
import {palette} from '../components/ui';
import {browserAlerts} from './browser-alerts';
import {useNativePush} from './native-push';
import {watchNativePushRefresh} from './native-push-refresh';
import type {BrowserAlertDelivery,BrowserAlertStatus} from '../../../../src/lib/browser-alert-delivery.js';
import {handoverAlertSnapshot,handoverAlertCopy,createHandoverAlertTracker,type HandoverAlertSnapshot,type HandoverAlert} from '../../../../src/lib/handover-alerts.js';
type Updates={unreadCount:number;transportUnreadCount:number;open:()=>void};
const Context=createContext<Updates>({unreadCount:0,transportUnreadCount:0,open:()=>{}});
const empty:ChatAlertSnapshot={unreadCount:0,waitingCount:0,items:[]};
export function ChatAlertProvider({children}:PropsWithChildren){
 const account=useAccount(),{t,locale}=useLanguage(),memberId=account.session?.user.id,request=account.request;
 const [guest,setGuest]=useState<{id:string;token:string;validUntil:number}|null>(null);
 const [guestReady,setGuestReady]=useState(false);
 const phone=useNativePush({session:account.session,busy:account.busy,request,guest,guestReady,locale});
 const identity=(memberId||'')+':'+(guest?.id||'')+':'+(guest?.validUntil||0);
 const [memberState,setMemberState]=useState({identity:'',feed:empty}),[guestState,setGuestState]=useState({identity:'',feed:empty}),[toastState,setToastState]=useState<{identity:string;value:ChatAlertEvent|null}>({identity:'',value:null}),[offlineState,setOfflineState]=useState({identity:'',value:false}),[open,setOpen]=useState(false);
 const memberFeed=memberState.identity===identity?memberState.feed:empty,guestFeed=guestState.identity===identity?guestState.feed:empty,toast=toastState.identity===identity?toastState.value:null,offline=offlineState.identity===identity&&offlineState.value;
 const [handoverState,setHandoverState]=useState<{identity:string;feed:HandoverAlertSnapshot}>({identity:'',feed:{unreadCount:0,items:[]}}),[handoverToastState,setHandoverToastState]=useState<{identity:string;value:HandoverAlert|null}>({identity:'',value:null});
 const handoverFeed=handoverState.identity===identity?handoverState.feed:{unreadCount:0,items:[]},handoverToast=handoverToastState.identity===identity?handoverToastState.value:null;
 const delivery=useRef<BrowserAlertDelivery|null>(null),[browserState,setBrowserState]=useState<{identity:string;status:BrowserAlertStatus}>({identity:'',status:'OFF'}),translate=useRef(t);
 const browserStatus=browserState.identity===identity?browserState.status:'OFF';
 useEffect(()=>{translate.current=t;},[t]);
 useEffect(()=>{const adapter=browserAlerts(identity);delivery.current=adapter;let live=true;void adapter.prepare().then(status=>{if(live){setBrowserState({identity,status});if(Platform.OS==='web'&&typeof window!=='undefined')window.dispatchEvent(new Event('loadgistic-chat-refresh'));}});return()=>{live=false;if(delivery.current===adapter)delivery.current=null;void adapter.dispose();};},[identity]);
 async function toggleBrowser(){const adapter=delivery.current;if(!adapter)return;const status=await adapter.toggle();if(delivery.current===adapter)setBrowserState({identity,status});if(Platform.OS==='web'&&typeof window!=='undefined')window.dispatchEvent(new Event('loadgistic-chat-refresh'));}
 const setToast=(value:ChatAlertEvent|null)=>setToastState({identity,value});
 const guestEpoch=useRef(0);
 const overlay=useRef({});useEffect(()=>{const source=overlay.current;blockChatReading(source,open);return()=>blockChatReading(source,false);},[open]);
 useEffect(()=>{
  let disposed=false;const restore=async()=>{const epoch=++guestEpoch.current;try{const raw=await Storage.getItemAsync(brokerageStorageKey),saved=raw?parseSavedChat(raw,Date.now()):null;
   if(!disposed&&epoch===guestEpoch.current)setGuest(previous=>{const next=saved?.kind==='ACTIVE'?{id:saved.requestId,token:saved.token,validUntil:saved.validUntil}:null;return previous?.id===next?.id&&previous?.token===next?.token&&previous?.validUntil===next?.validUntil?previous:next;});
  }catch{if(!disposed&&epoch===guestEpoch.current)setGuest(null);}finally{if(!disposed&&epoch===guestEpoch.current)setGuestReady(true);}};
  void restore();const stop=watchBrokerageAccess(()=>{void restore();}),subscription=AppState.addEventListener('change',state=>{if(state==='active')void restore();});return()=>{disposed=true;stop();subscription.remove();};
 },[]);
 // One bounded poller for both independent authorities; neither can grant access to the other.
 useEffect(()=>{
  let disposed=false,running=false,failures=0,timer:ReturnType<typeof setTimeout>|undefined;
  const memberTracker=createChatAlertTracker(),guestTracker=createChatAlertTracker(),handoverTracker=createHandoverAlertTracker();
  const poll=async()=>{if(!disposed&&delivery.current)setBrowserState(previous=>{const status=delivery.current?.status()||'OFF';return previous.identity===identity&&previous.status===status?previous:{identity,status};});if(disposed||running||(AppState.currentState!=='active'&&!delivery.current?.enabled()))return;running=true;let failed=false;const events:ChatAlertEvent[]=[],memberTrackerScope:string[]=[],guestTrackerScope:string[]=[];
   const member=async()=>{if(!memberId)return;try{const data=chatAlertSnapshot(await request('/api/mobile/chat-alerts'));if(!disposed){setMemberState({identity,feed:data});memberTrackerScope.push(...data.items.map(item=>item.kind==='SUPPORT'?'/support-chat?id='+item.id:'/arrange-transport'));events.push(...memberTracker.next(data));}}
    catch(error){failed=true;if(!disposed&&[401,403].includes((error as {status?:number}).status||0)){setMemberState({identity,feed:empty});memberTracker.reset();void delivery.current?.dispose();}}};
   const handover=async()=>{if(!memberId)return;try{const data=handoverAlertSnapshot(await request('/api/mobile/notifications/handover'));if(!disposed){setHandoverState({identity,feed:data});void delivery.current?.reconcile('handover',data.items.filter(item=>item.unread).map(item=>'/shipment-detail?id='+item.id));const changes=handoverTracker.next(data);if(changes.length){setHandoverToastState({identity,value:changes[changes.length-1]});for(const item of changes)void delivery.current?.deliver({eventKey:'handover:'+item.id+':'+item.approvedAt,body:translate.current(handoverAlertCopy(item)),href:'/shipment-detail?id='+item.id});}}}catch(error){failed=true;if(!disposed&&[401,403].includes((error as {status?:number}).status||0)){setHandoverState({identity,feed:{unreadCount:0,items:[]}});setHandoverToastState({identity,value:null});handoverTracker.reset();void delivery.current?.dispose();}}};
   const visitor=async()=>{if(!guest)return;if(guest.validUntil<=Date.now()){if(!disposed)setGuest(null);return;}try{const data=chatAlertSnapshot(await apiRequest('/api/mobile/brokerage/alerts',{token:guest.token}));if(!disposed){setGuestState({identity,feed:data});guestTrackerScope.push(...data.items.map(()=>'/arrange-transport'));events.push(...guestTracker.next(data));}}
    catch(error){failed=true;if(!disposed&&(error as {status?:number}).status===403){setGuestState({identity,feed:empty});setGuest(null);guestTracker.reset();}}};
   await Promise.allSettled([member(),visitor(),handover()]);if(!disposed){void delivery.current?.reconcile('chat',[...memberTrackerScope,...guestTrackerScope]);const relevant=events.filter(change=>change.event!=='MESSAGE'||!isChatMessageVisible(change.item.kind+':'+change.item.id,change.item.incomingSequence));if(relevant.length){setToastState({identity,value:relevant[relevant.length-1]});for(const change of relevant)void delivery.current?.deliver({eventKey:JSON.stringify([change.item.kind,change.item.id,change.event,change.item.assignmentVersion,change.item.incomingSequence,change.item.endedAt]),body:translate.current(chatAlertCopy(change)),href:change.item.kind==='SUPPORT'?'/support-chat?id='+change.item.id:'/arrange-transport'});}setOfflineState({identity,value:failed});failures=failed?Math.min(failures+1,3):0;timer=setTimeout(poll,Math.min(30000,(AppState.currentState==='active'?5000:15000)*2**failures));}running=false;
  };
  const resume=()=>{clearTimeout(timer);void poll();};const stopPushRefresh=watchNativePushRefresh(resume);void poll();const subscription=AppState.addEventListener('change',state=>{if(state==='active')resume();});if(Platform.OS==='web'&&typeof window!=='undefined')window.addEventListener('loadgistic-chat-refresh',resume);return()=>{disposed=true;stopPushRefresh();clearTimeout(timer);subscription.remove();if(Platform.OS==='web'&&typeof window!=='undefined')window.removeEventListener('loadgistic-chat-refresh',resume);};
 },[memberId,request,guest,identity]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToastState({identity,value:null}),10000);return()=>clearTimeout(timer);},[toast,identity]);
 useEffect(()=>{if(!handoverToast)return;const timer=setTimeout(()=>setHandoverToastState({identity,value:null}),10000);return()=>clearTimeout(timer);},[handoverToast,identity]);
 function openHandover(item:HandoverAlert){setOpen(false);setHandoverToastState({identity,value:null});void request('/api/mobile/notifications/handover',{id:item.id,approvedAt:item.approvedAt}).then(value=>setHandoverState({identity,feed:handoverAlertSnapshot(value)})).catch(()=>setOfflineState({identity,value:true}));router.navigate({pathname:'/shipment-detail',params:{id:item.id}});}
 function openChat(item:ChatAlertItem){setOpen(false);setToast(null);router.navigate((item.kind==='SUPPORT'?{pathname:'/support-chat',params:{id:item.id}}:'/arrange-transport') as Href);}
 const items=[...memberFeed.items,...guestFeed.items],count=memberFeed.unreadCount+guestFeed.unreadCount+handoverFeed.unreadCount;
 const showUpdates=useCallback(()=>setOpen(true),[]),transportUnreadCount=guestFeed.unreadCount;
 const context=useMemo(()=>({unreadCount:count,transportUnreadCount,open:showUpdates}),[count,transportUnreadCount,showUpdates]);
 return <Context.Provider value={context}>{children}
  {handoverToast?<View accessibilityLiveRegion="polite" style={styles.toast}><AppIcon name="seen" size={19} color={palette.teal}/><View style={{flex:1,gap:3}}><Text style={styles.toastText}>{t(handoverAlertCopy(handoverToast))}</Text><Pressable accessibilityRole="button" onPress={()=>openHandover(handoverToast)} style={{paddingVertical:7}}><Text style={{color:palette.teal,fontWeight:'700'}}>{t('Open Tracking')}</Text></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel={t('Dismiss notification')} onPress={()=>setHandoverToastState({identity,value:null})} style={styles.close}><AppIcon name="close" size={20}/></Pressable></View>:toast&&<View accessibilityLiveRegion="polite" style={styles.toast}><AppIcon name="bell" size={19} color={palette.teal}/><View style={{flex:1,gap:3}}><Text style={styles.toastText}>{t(chatAlertCopy(toast))}</Text><Pressable accessibilityRole="button" onPress={()=>openChat(toast.item)} style={{paddingVertical:7}}><Text style={{color:palette.teal,fontWeight:'700'}}>{t('Open chat')}</Text></Pressable></View><Pressable accessibilityRole="button" accessibilityLabel={t('Dismiss notification')} onPress={()=>setToast(null)} style={styles.close}><AppIcon name="close" size={20}/></Pressable></View>}
  <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={styles.backdrop}><Pressable style={StyleSheet.absoluteFill} accessible={false} onPress={()=>setOpen(false)}/><View style={styles.sheet}><View style={styles.heading}><Text style={styles.title}>{t(memberId?'Updates':'Chat updates')}</Text><Pressable accessibilityRole="button" accessibilityLabel={t('Close')} onPress={()=>setOpen(false)} style={styles.close}><AppIcon name="close"/></Pressable></View><Text style={styles.meta}>{t(phone.status==='ON'?'Notifications for your chats and Tracking.':'Alerts while you’re using this app.')}</Text>{Platform.OS==='web'&&browserStatus!=='UNSUPPORTED'&&<><Pressable accessibilityRole="button" accessibilityState={{disabled:browserStatus==='DENIED'}} disabled={browserStatus==='DENIED'} onPress={()=>void toggleBrowser()} style={styles.row}><AppIcon name="bell" color={palette.teal}/><Text style={[styles.toastText,{flex:1}]}>{t(browserStatus==='ON'?'Browser alerts on':browserStatus==='DENIED'?'Browser alerts blocked':'Enable browser alerts')}</Text></Pressable><Text style={styles.meta}>{t(browserStatus==='DENIED'?'Allow notifications in your browser’s site settings.':browserStatus==='UNAVAILABLE'?'Browser alerts unavailable. In-app updates still work.':'Keep Loadgistic open to receive browser alerts.')}</Text></>}{phone.status!=='UNSUPPORTED'&&<><Pressable accessibilityRole="button" accessibilityState={{disabled:phone.status==='BUSY'||(!phone.optedIn&&(!memberId&&!guest||phone.status==='DENIED'))}} disabled={phone.status==='BUSY'||(!phone.optedIn&&(!memberId&&!guest||phone.status==='DENIED'))} onPress={()=>void phone.toggle()} style={styles.row}><AppIcon name="bell" color={palette.teal}/><Text style={[styles.toastText,{flex:1}]}>{t(phone.status==='BUSY'?'Connecting phone notifications…':phone.status==='ON'?'Phone notifications on':phone.optedIn?'Turn off phone notifications':phone.status==='DENIED'?'Phone notifications blocked':'Enable phone notifications')}</Text></Pressable><Text style={styles.meta}>{t(phone.status==='ON'?'Receive chat and Tracking updates even when the app is closed.':phone.status==='DENIED'?'Allow notifications in your phone’s app settings.':(!memberId&&!guest)?'Start a chat or sign in to enable phone notifications.':phone.status==='UNAVAILABLE'?'Phone notifications need the latest Android app and a connection.':'Receive chat replies and unloading approval on your phone.')}</Text>{phone.error&&<Text accessibilityRole="alert" style={styles.meta}>{t(phone.error)}</Text>}</>}{offline&&<Text accessibilityLiveRegion="polite" style={styles.meta}>{t('Updates paused. Reconnecting…')}</Text>}
   <ScrollView contentContainerStyle={{gap:8,paddingVertical:12}}>{handoverFeed.items.map(item=><Pressable key={item.id} accessibilityRole="button" onPress={()=>openHandover(item)} style={styles.row}><AppIcon name="seen" color={palette.teal}/><View style={{flex:1,gap:4}}><Text style={styles.toastText}>{t(handoverAlertCopy(item))}</Text><Text style={styles.reference}>#{item.id.slice(0,8).toUpperCase()}</Text><Text style={styles.meta}>{t('Open Tracking')}</Text></View>{item.unread&&<Text style={styles.count}>{t('New')}</Text>}</Pressable>)}{items.length?items.map(item=><Pressable key={item.kind+item.id} accessibilityRole="button" onPress={()=>openChat(item)} style={styles.row}><View style={{flex:1,gap:4}}><Text style={styles.toastText}>{t(item.kind==='SUPPORT'?'Support':'Arrange transport')}</Text><Text style={styles.reference}>#{item.id.slice(0,8).toUpperCase()}</Text><Text style={styles.meta}>{t(item.status==='CLOSED'?'Resolved':item.endedAt?'Chat ended':item.assigned?'Assigned':'Waiting for an agent')}</Text></View>{item.unreadCount>0&&<Text style={styles.count}>{t('{count} unread',{count:item.unreadCount})}</Text>}</Pressable>):!handoverFeed.items.length&&<Text style={styles.meta}>{t(memberId?'No updates yet.':'No chat updates yet.')}</Text>}{memberId&&<Pressable accessibilityRole="button" onPress={()=>{setOpen(false);router.navigate('/support');}} style={styles.row}><AppIcon name="help" color={palette.teal}/><Text style={styles.toastText}>{t('Support home')}</Text></Pressable>}</ScrollView>
  </View></View></Modal>
 </Context.Provider>;
}
export function useChatUpdates(){return useContext(Context);}
export function ChatUpdatesButton(){const updates=useChatUpdates(),{t}=useLanguage();return <Pressable accessibilityRole="button" accessibilityLabel={updates.unreadCount?t('Updates · {count} new or waiting',{count:updates.unreadCount}):t('Updates')} onPress={updates.open} style={styles.bell}><AppIcon name="bell" color={palette.teal}/>{updates.unreadCount>0&&<View style={styles.badge}><Text style={styles.badgeText}>{updates.unreadCount>99?'99+':updates.unreadCount}</Text></View>}</Pressable>;}
const styles=StyleSheet.create({bell:{width:44,minHeight:48,alignItems:'center',justifyContent:'center'},badge:{position:'absolute',right:0,top:2,minWidth:19,paddingHorizontal:4,height:19,borderRadius:12,alignItems:'center',justifyContent:'center',backgroundColor:'#ffcb05'},badgeText:{color:palette.ink,fontSize:10,fontWeight:'800'},toast:{position:'absolute',top:65,left:12,right:12,maxWidth:460,alignSelf:'center',backgroundColor:'#fff',borderWidth:1,borderColor:'#b9ded9',borderRadius:14,padding:14,flexDirection:'row',gap:10,elevation:6,boxShadow:'0 4px 20px rgba(23,44,70,.14)'},toastText:{fontSize:14,lineHeight:20,fontWeight:'700',color:palette.ink},close:{width:44,height:44,alignItems:'center',justifyContent:'center'},backdrop:{flex:1,backgroundColor:'rgba(23,44,70,.18)',alignItems:'center',justifyContent:'center',padding:16},sheet:{width:'100%',maxWidth:440,maxHeight:'75%',backgroundColor:'#fff',padding:18,borderRadius:18},heading:{flexDirection:'row',justifyContent:'space-between',alignItems:'center'},title:{flex:1,flexShrink:1,minWidth:0,fontSize:22,fontWeight:'700',color:palette.ink},reference:{fontSize:11,color:palette.muted},meta:{fontSize:13,lineHeight:19,color:palette.muted},row:{flexDirection:'row',gap:10,alignItems:'center',borderWidth:1,borderColor:palette.border,borderRadius:12,padding:12,minHeight:52},count:{fontSize:12,color:palette.teal,fontWeight:'700'}});
