import { useCallback,useReducer,useState } from 'react';
import { useFocusEffect } from 'expo-router';
import { ActivityIndicator,AppState,Text,View } from 'react-native';
import * as SecureStore from '../session/storage';
import * as Crypto from 'expo-crypto';
import { createBrokerageController } from '../session/brokerage-controller';
import { apiRequest } from '../api/http';
import { useForegroundRefresh } from '../hooks/foreground-refresh';
import { Page,Copy,Card,Field,Button,ErrorText,palette } from '../components/ui';
const key='loadgistic.brokerage.v1';
export default function ArrangeTransport(){
 const [,render]=useReducer(n=>n+1,0),[controller]=useState(()=>createBrokerageController({now:Date.now,uuid:Crypto.randomUUID,secret:async()=>Array.from(await Crypto.getRandomBytesAsync(32),byte=>byte.toString(16).padStart(2,'0')).join(''),changed:render,request:apiRequest,read:()=>SecureStore.getItemAsync(key),write:value=>SecureStore.setItemAsync(key,value,{keychainAccessible:SecureStore.WHEN_UNLOCKED_THIS_DEVICE_ONLY}),remove:()=>SecureStore.deleteItemAsync(key)}));
 const state=controller.snapshot(),chat=state.chat;
 const [name,setName]=useState(''),[phone,setPhone]=useState(''),[origin,setOrigin]=useState(''),[destination,setDestination]=useState(''),[body,setBody]=useState(''),[before,setBefore]=useState<number|undefined>(),[confirm,setConfirm]=useState(false);
 useFocusEffect(useCallback(()=>{controller.setVisible(AppState.currentState==='active');if(!controller.snapshot().ready)void controller.restore();else void controller.refresh(before);const subscription=AppState.addEventListener('change',next=>{controller.setVisible(next==='active');if(next==='active')void controller.refresh(before);});return()=>{controller.setVisible(false);subscription.remove();};},[controller,before]));
 const refresh=useCallback(()=>controller.refresh(before),[controller,before]);
 useForegroundRefresh(refresh,Boolean(chat)&&!before&&!state.busy&&!chat?.request.endedAt&&chat?.request.status!=='CLOSED');
 const pending=state.saved?.kind==='ACTIVE'?state.saved.pending:undefined,ended=Boolean(chat?.request.endedAt||chat?.request.status==='CLOSED'),draft=state.saved?.kind==='DRAFT'?state.saved.intake:null;
 return <Page><ErrorText message={state.error}/>{!state.ready&&<ActivityIndicator accessibilityLabel="Opening your conversation"/>}{state.cleanupRequired&&<Button message="Retry clearing chat access" onPress={()=>{void controller.clear();}}/>}
 {state.ready&&state.saved?.kind!=='ACTIVE'&&<><Copy message={"Live chat with our transport team"}/><Copy message={"Tell us where your load is going. We’ll help you find a transporter and discuss the details."}/><Card>
 <Field message="From" value={draft?.origin||origin} onChangeText={setOrigin} maxLength={160} editable={!state.busy&&!draft}/><Field message="To" value={draft?.destination||destination} onChangeText={setDestination} maxLength={160} editable={!state.busy&&!draft}/><Field message="Your name" value={draft?.name||name} onChangeText={setName} maxLength={100} editable={!state.busy&&!draft}/><Field message="Phone number" value={draft?.phone||phone} onChangeText={setPhone} keyboardType="phone-pad" maxLength={30} editable={!state.busy&&!draft}/>
 <Copy message={"We can call this number if you leave the chat. No email or account needed."}/><Button label={draft?'Retry starting chat':'Start chat'} busy={state.busy} disabled={state.cleanupRequired} onPress={()=>{void controller.start({name,phone,origin,destination});}}/>{!!draft&&<Copy message={"Your request details are saved on this phone. Retrying checks the same request without creating a duplicate."}/>}</Card></>}
 {state.saved?.kind==='ACTIVE'&&<><Button secondary message="Refresh conversation" busy={state.busy} onPress={()=>{void refresh();}}/>{!chat&&!state.error&&<ActivityIndicator accessibilityLabel="Loading conversation"/>}{chat&&<><Copy>{chat.request.origin} → {chat.request.destination}</Copy><Copy>{ended?(chat.request.status==='CLOSED'?'Request resolved · chat history':'Chat ended. Our team can still call you.'):chat.request.assignedName?`${chat.request.assignedName} is helping with your request.`:'Your request is with our brokerage team. Leave a message while you wait for someone to join.'}</Copy>
 {chat.hasOlder&&<Button secondary message="Older messages" disabled={state.busy} onPress={()=>{const sequence=chat.messages[0]?.sequence;if(sequence){setBefore(sequence);}}}/>}{before&&<Button secondary message="Latest messages" onPress={()=>{setBefore(undefined);}}/>}
 {chat.messages.map(item=><View key={item.id} style={{padding:14,gap:6,borderRadius:14,backgroundColor:item.kind==='VISITOR'?'#eaf5f4':'#f2f5f7',marginLeft:item.kind==='VISITOR'?20:0,marginRight:item.kind==='BROKER'?20:0}}><Text style={{fontWeight:'700',color:palette.ink}}>{item.name}</Text><Text selectable style={{color:palette.ink,lineHeight:23}}>{item.body}</Text><Copy>{new Date(item.createdAt).toLocaleString()}</Copy></View>)}
 {!ended&&!before&&<Card><Field message="Message to transport team" value={pending?.body||body} onChangeText={setBody} multiline maxLength={2000} editable={!state.busy&&!pending}/><Button label={pending?'Retry sending message':'Send message'} busy={state.busy} disabled={!pending&&!body.trim()} onPress={()=>{void controller.send(body).then(()=>{if(!controller.snapshot().error)setBody('');});}}/>{pending&&<Copy message={"Delivery is not confirmed yet. Retry this message safely."}/>}
 {!confirm?<Button secondary message="End chat" disabled={state.busy} onPress={()=>setConfirm(true)}/>:<><Copy message={"End messaging? Our team will keep your request and may still call you."}/><Button message="Confirm end chat" busy={state.busy} onPress={()=>{void controller.end().then(()=>setConfirm(false));}}/><Button secondary message="Keep chatting" disabled={state.busy} onPress={()=>setConfirm(false)}/></>}</Card>}
 {ended&&<Button message="Start a new request" busy={state.busy} onPress={()=>{void controller.newChat().then(()=>{setBody('');setBefore(undefined);});}}/>}</>}</>}</Page>;
}
