import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { getDriverAccess, listLoads, listOwnTruckRouteOptions } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { Flash } from '@/components/flash';
import { priceDisplay } from '@/lib/ui';
import { StatusPill } from '@/components/status-pill';
import { VEHICLE_CONFIGURATIONS } from '@/lib/vehicle-configurations';
import { Route, Search, SlidersHorizontal, X } from 'lucide-react';

export default async function LoadsPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(['TRANSPORTER','DRIVER','ADMIN']); const access=getDriverAccess(user); const canBrowse=access?.can_browse_load_board!==false; const canNegotiate=access?.can_negotiate_loads!==false&&access?.can_contact_businesses!==false; const query=await searchParams; const mode=query.mode||'ALL'; const filters={q:query.q||'',origin:query.origin||'',destination:query.destination||'',loadType:query.loadType||'',vehicleCategory:query.vehicleCategory||'',matchCapacityId:query.matchCapacityId||''}; const loads:any[]=listLoads(user,mode,filters); const truckRoutes:any[]=listOwnTruckRouteOptions(user); const hasFilters=mode!=='ALL'||Object.values(filters).some(Boolean);
 return <div className="page"><PageHeader title="Load Board" subtitle="Direct requests, partner loads, and open freight demand from verified Businesses."/><Flash error={query.error} success={query.success}/>
 {!canBrowse?<div className="permission-note"><SlidersHorizontal aria-hidden="true"/><div><strong>Load Board access is managed by your fleet owner</strong><span>You can continue using duty and assigned tracking workflows.</span></div></div>:<>
 <form className="board-filter-panel" method="get">
   <div className="board-filter-heading"><SlidersHorizontal aria-hidden="true"/><div><h2>Find demand for a truck</h2><p>Search the board or rank loads against one truck's recorded route.</p></div></div>
   <div className="board-filter-grid">
     <div className="form-group filter-search"><label htmlFor="load-search"><Search aria-hidden="true"/>Search</label><input id="load-search" name="q" defaultValue={filters.q} placeholder="Load, Business, cargo, or city"/></div>
     {truckRoutes.length?<div className="form-group filter-match"><label htmlFor="load-match"><Route aria-hidden="true"/>Match one truck route</label><select id="load-match" name="matchCapacityId" defaultValue={filters.matchCapacityId}><option value="">Do not rank by a truck</option>{truckRoutes.map(truck=><option value={truck.id} key={truck.id}>{truck.label} · {truck.origin} → {truck.destination}</option>)}</select></div>:null}
     <div className="form-group"><label htmlFor="load-origin">Corridor city 1</label><input id="load-origin" name="origin" defaultValue={filters.origin} placeholder="Addis Ababa"/></div>
     <div className="form-group"><label htmlFor="load-destination">Corridor city 2</label><input id="load-destination" name="destination" defaultValue={filters.destination} placeholder="Hawassa"/></div>
     <div className="form-group"><label htmlFor="load-type">Load size</label><select id="load-type" name="loadType" defaultValue={filters.loadType}><option value="">FTL or PTL</option><option value="FTL">FTL</option><option value="PTL">PTL</option></select></div>
     <div className="form-group"><label htmlFor="load-truck-type">Cargo configuration</label><select id="load-truck-type" name="vehicleCategory" defaultValue={filters.vehicleCategory}><option value="">All truck types</option>{VEHICLE_CONFIGURATIONS.map(type=><option value={type.name} key={type.name}>{type.name}</option>)}</select></div>
     <div className="form-group"><label htmlFor="load-visibility">Board view</label><select id="load-visibility" name="mode" defaultValue={mode}><option value="ALL">All permitted loads</option><option value="DIRECT">Direct</option><option value="PARTNERS">My Partners</option><option value="OPEN">Open Loads</option></select></div>
   </div>
   <div className="board-filter-actions"><button className="button icon-button-label"><Search aria-hidden="true"/>Show matching loads</button>{hasFilters?<Link href="/app/loads" className="button secondary icon-button-label"><X aria-hidden="true"/>Clear</Link>:null}<span className="meta">{loads.length} {loads.length===1?'load':'loads'} shown</span></div>
 </form>
 <div className="stack" data-testid="load-list">{loads.map((load:any)=><article className="card load-board-card" key={load.id}><div className="load-board-layout"><div><div className="status-row"><StatusPill status={load.distribution_mode}/><span className="status">{load.shipper_name}</span><span className="status green">{load.load_type||'Load type missing'}</span>{load.route_match_label?<span className={`route-match match-${load.route_match_score}`}><Route aria-hidden="true"/>{load.route_match_label}</span>:null}</div><h3>{load.title}</h3><div className="route">{load.origin}<span>→</span>{load.destination}</div><div className="meta">Pick up before {load.pickup_date} · {load.vehicle_category||'Vehicle discussed directly'}</div><p>{load.cargo_description}{load.estimated_weight?` · ${load.estimated_weight} kg`:''}</p></div><div className="load-board-actions"><strong>{priceDisplay(load)}</strong><div className="meta">Posted {new Date(load.created_at).toLocaleString()}</div><div className="hero-actions"><Link className="button secondary" href={`/app/shipments/${load.id}`}>View details</Link>{load.load_contact_phone?<a className="button secondary" href={`tel:${load.load_contact_phone}`}>Call Business</a>:null}{canNegotiate?(!load.interested?<form action={`/api/shipments/${load.id}/interest`} method="post"><button className="button">Express interest</button></form>:<StatusPill status="Contacted"/>):null}</div></div></div></article>)}</div>{!loads.length?<div className="empty-state">No loads match these filters.</div>:null}</>}</div>;
}
