import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { getBusinessTrackingAccessCode, getDriverAccess, getShipmentForUser, paginateResults } from '@/lib/repository.js';
import { nextStatuses } from '@/lib/domain.js';
import { priceDisplay } from '@/lib/ui';
import { PageHeader } from '@/components/page-header';
import { Pagination } from '@/components/pagination';
import { StatusPill } from '@/components/status-pill';
import { Flash } from '@/components/flash';
import { ShipmentTrackingControls } from '@/components/shipment-tracking-controls';
import { KeyRound, PackageSearch, Phone, Save, ShieldAlert, Star, Upload } from 'lucide-react';

export default async function ShipmentDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); const access=getDriverAccess(user); const canNegotiate=access?.can_negotiate_loads!==false&&access?.can_contact_businesses!==false&&access?.can_browse_load_board!==false; const {id}=await params; const query=await searchParams; const shipment:any=getShipmentForUser(user,id); if(!shipment)notFound();
 const next=nextStatuses(shipment.service_mode,shipment.operational_status);
 const ownerOrganizationId=shipment.load_owner_organization_id||shipment.shipper_organization_id;
 const isParty=user.role==='ADMIN'||Boolean(user.organization_id&&[ownerOrganizationId,shipment.shipper_organization_id,shipment.receiver_organization_id,shipment.provider_organization_id].includes(user.organization_id))||Boolean(user.provider_profile_id&&shipment.provider_profile_id===user.provider_profile_id);
 const canOperate=isParty&&['TRANSPORTER','DRIVER','ADMIN'].includes(user.role);
 const directMatch=shipment.distribution_mode==='DIRECT_TO_PROVIDER'&&((['TRANSPORTER','DRIVER'].includes(user.role)&&user.organization_id&&shipment.provider_organization_id===user.organization_id)||(user.role==='DRIVER'&&user.provider_profile_id&&shipment.provider_profile_id===user.provider_profile_id));
 const isLoadOwner=shipment.service_mode==='FREIGHT'&&(user.role==='ADMIN'||ownerOrganizationId===user.organization_id);
 const canManageTracking=user.role==='ADMIN'||Boolean(['SHIPPER','RECEIVER'].includes(user.role)&&user.organization_id&&[ownerOrganizationId,shipment.shipper_organization_id,shipment.receiver_organization_id].includes(user.organization_id));
 const canOpenCustomerTracking=Boolean(['SHIPPER','RECEIVER'].includes(user.role)&&user.organization_id&&ownerOrganizationId===user.organization_id);
 const trackingAccessCode=canOpenCustomerTracking?getBusinessTrackingAccessCode(user,shipment.id):null;
 const needsReceiverContact=shipment.service_mode==='FREIGHT'&&shipment.operational_status==='AGREED'&&(!shipment.receiver_first_name||!shipment.receiver_phone);
 const ownInterest=shipment.interests.find((interest:any)=>user.organization_id?interest.provider_organization_id===user.organization_id:interest.provider_profile_id===user.provider_profile_id);
 const activeLoadProof=shipment.load_proof_shares?.find((share:any)=>!share.revoked_at&&new Date(share.expires_at).getTime()>Date.now());
 const businessParties=[shipment.shipper_organization_id,shipment.receiver_organization_id].filter((value,index,all)=>Boolean(value)&&all.indexOf(value)===index);
 const ownBusinessReview=shipment.business_reviews.find((review:any)=>review.reviewer_organization_id===user.organization_id);
 const canReviewBusiness=shipment.operational_status==='COMPLETED'&&businessParties.length===2&&businessParties.includes(user.organization_id)&&!ownBusinessReview;
 const reviewTarget=user.organization_id===shipment.shipper_organization_id?shipment.receiver_name:shipment.shipper_name;
 const eventResult:any=paginateResults(shipment.events,{page:query.eventPage,pageSize:12});
 const proofResult:any=paginateResults(shipment.proofs,{page:query.proofPage,pageSize:10});
 const noteResult:any=paginateResults(shipment.notes,{page:query.notePage,pageSize:10});
 const shareResult:any=paginateResults(shipment.load_proof_shares||[],{page:query.sharePage,pageSize:10});
 const detailPages={eventPage:query.eventPage,proofPage:query.proofPage,notePage:query.notePage,sharePage:query.sharePage};
 return <div className="page"><PageHeader title={`${shipment.code} · ${shipment.title}`} subtitle={`${shipment.origin} → ${shipment.destination}`} action={<StatusPill status={shipment.operational_status}/>}/><Flash error={query.error} success={query.success}/>
 <div className="two-col"><div className="stack"><section className="card"><div className="split"><div><span className="meta">Price</span><h3>{priceDisplay(shipment)}</h3></div><div><span className="meta">Load owner</span><h3>{shipment.load_owner_name}</h3></div><div><span className="meta">Shipper</span><h3>{shipment.shipper_handle?<Link href={`/app/providers/${shipment.shipper_handle}`}>{shipment.shipper_name}</Link>:shipment.shipper_name||'Not selected'}</h3></div><div><span className="meta">Receiver</span><h3>{shipment.receiver_handle?<Link href={`/app/providers/${shipment.receiver_handle}`}>{shipment.receiver_name}</Link>:shipment.receiver_name||'Not selected'}</h3>{isParty&&shipment.receiver_first_name?<div className="meta">{shipment.receiver_first_name} · {shipment.receiver_phone}</div>:null}</div><div><span className="meta">Provider</span><h3>{shipment.provider_name||shipment.provider_profile_name||'Not assigned'}</h3></div><div><span className="meta">Pick up before</span><h3>{shipment.pickup_date}</h3></div><div><span className="meta">Drop off before</span><h3>{shipment.delivery_date||'Not set'}</h3></div></div><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'20px 0'}}/><h3>Load detail</h3><p>{shipment.cargo_description}</p><div className="meta">{shipment.vehicle_category||'Cargo configuration discussed directly'}{shipment.load_type?` · ${shipment.load_type.replaceAll('_',' ')}`:''}</div></section>
 {shipment.service_mode==='FREIGHT'?<section className="load-policy-banner"><span className="status">{shipment.load_type||'Not specified'}</span><div><strong>{shipment.load_type==='FTL'?'Full truckload required':'Partial truckload is suitable'}</strong><span>{shipment.load_type==='FTL'?'This load needs a dedicated truck.':'This load can use available shared cargo space.'}</span></div></section>:null}
 <section className="card"><h2 style={{fontSize:'1.4rem'}}>Tracking timeline</h2><ol className="timeline">{eventResult.items.map((event:any)=><li key={event.id}><strong>{event.event_type==='LOCATION'?'Location update':event.event_type==='TRACKING_MODE'?'Tracking preference changed':event.status.replaceAll('_',' ')}</strong><div>{event.note||'Status updated'}</div>{event.location_area?<div className="tracking-location-line"><strong>{event.location_area}</strong><span>{event.location_source==='DEVICE_OBSCURED'?`Approximate device area · ${event.location_precision_km} km privacy zone`:'Driver-declared general area'}</span></div>:null}<div className="meta">{event.actor_name||'Loadgistic'} · {new Date(event.created_at).toLocaleString()}</div></li>)}</ol><Pagination path={`/app/shipments/${id}`} query={{...detailPages,eventPage:undefined}} page={eventResult.page} pageCount={eventResult.pageCount} total={eventResult.total} pageParam="eventPage"/></section>
 {proofResult.total?<section className="card"><h2 style={{fontSize:'1.4rem'}}>Proof</h2><div className="stack">{proofResult.items.map((proof:any)=><div className="card" key={proof.id}><strong>{proof.proof_type} Proof</strong><div className="meta">Uploaded by {proof.uploaded_by_name} · {new Date(proof.created_at).toLocaleString()}</div><p>{proof.note}</p><a className="button secondary small" href={`/api/files/proof/${proof.id}`} target="_blank">Open file</a></div>)}</div><Pagination path={`/app/shipments/${id}`} query={{...detailPages,proofPage:undefined}} page={proofResult.page} pageCount={proofResult.pageCount} total={proofResult.total} pageParam="proofPage"/></section>:null}
 </div>
 <aside className="stack">
	  {isLoadOwner&&shipment.operational_status==='AGREED'?<section className="card"><h3>Receiver contact</h3><p className="muted">Required before the transporter can assign this load. Only load parties can see it.</p><form action={`/api/shipments/${shipment.id}/receiver-contact`} method="post" className="stack"><div className="form-group"><label htmlFor="receiver-first-name">Receiver first name</label><input id="receiver-first-name" name="receiverFirstName" defaultValue={shipment.receiver_first_name||''} required/></div><div className="form-group"><label htmlFor="receiver-phone"><Phone aria-hidden="true"/>Receiver phone</label><input id="receiver-phone" name="receiverPhone" type="tel" defaultValue={shipment.receiver_phone||''} required/></div><button className="button icon-button-label"><Save aria-hidden="true"/>Save receiver contact</button></form></section>:null}
	  {directMatch&&canNegotiate&&shipment.service_mode==='FREIGHT'&&shipment.commercial_status!=='AGREED'?<section className="card"><h3>Direct request</h3><p className="muted">Accept only after you agree directly with the business.</p><form action={`/api/shipments/${shipment.id}/accept`} method="post"><button className="button" style={{width:'100%'}}>Accept direct request</button></form></section>:null}
  {canOperate?<ShipmentTrackingControls shipmentId={shipment.id} trackingMode={shipment.tracking_mode} nextStatuses={next} needsReceiverContact={needsReceiverContact} operationalStatus={shipment.operational_status} allowDeviceLocation={user.role==='DRIVER'} loadType={shipment.load_type}/>:null}
	  {['TRANSPORTER','DRIVER'].includes(user.role)&&shipment.load_contact_phone?<section className="card"><h3>Business contact</h3><a className="button secondary icon-button-label" href={`tel:${shipment.load_contact_phone}`}><Phone aria-hidden="true"/>Call {shipment.load_contact_phone}</a></section>:null}
	  {['TRANSPORTER','DRIVER'].includes(user.role)&&canNegotiate&&!isParty&&shipment.service_mode==='FREIGHT'&&shipment.operational_status==='POSTED'&&!shipment.interests.some((i:any)=>(user.organization_id?i.provider_organization_id===user.organization_id:i.provider_profile_id===user.provider_profile_id))?<section className="card"><h3>Interested in this load?</h3><form action={`/api/shipments/${shipment.id}/interest`} method="post" className="stack"><label htmlFor="interest-note">Message to the business (optional)</label><textarea id="interest-note" name="note"/><button className="button">Express interest</button></form></section>:null}
	  {['TRANSPORTER','DRIVER'].includes(user.role)&&canNegotiate&&ownInterest?<section className="card"><h3>Load-size proof</h3>{ownInterest.created_by_name?<p className="meta">Interest sent by {ownInterest.created_by_name}.</p>:null}{activeLoadProof?<><p className="muted">The Business shared this proof only with you. Access ends {new Date(activeLoadProof.expires_at).toLocaleString()}.</p><a className="button secondary" href={`/api/files/load-proof/${activeLoadProof.id}`} target="_blank">Open load proof</a></>:ownInterest.proof_request_id?<p className="muted">Requested {new Date(ownInterest.proof_requested_at).toLocaleString()}. The Business will choose whether to share proof with you.</p>:<><p className="muted">Ask the Business for private evidence of the load size or quantity.</p><form action={`/api/shipments/${shipment.id}/load-proof/request`} method="post"><button className="button secondary">Request load proof</button></form></>}</section>:null}
	  {isLoadOwner&&shipment.interests.length?<section className="card"><h3>Share load proof</h3><p className="muted">Choose exactly one interested transporter. Their access is temporary and private.</p><form action={`/api/shipments/${shipment.id}/load-proof/share`} method="post" encType="multipart/form-data" className="stack"><div className="form-group"><label htmlFor="load-proof-interest">Interested transporter</label><select id="load-proof-interest" name="interestId" required><option value="">Choose an interested transporter</option>{shipment.interests.map((interest:any)=><option value={interest.id} key={interest.id}>{interest.organization_name||interest.provider_name}{interest.created_by_name?` · ${interest.created_by_name}`:''}{interest.proof_request_id?' · Proof requested':''}</option>)}</select></div><div className="form-group"><label htmlFor="load-proof-file">Proof of load size or quantity</label><input id="load-proof-file" name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></div><div className="form-group"><label htmlFor="load-proof-note">Context (optional)</label><input id="load-proof-note" name="note" placeholder="Example: Current pallet count and loading area"/></div><button className="button secondary">Share temporary proof</button></form>{shareResult.total?<><div className="temporary-share-list">{shareResult.items.map((share:any)=><div key={share.id}><strong>{share.organization_name||share.provider_name}</strong><span>{share.revoked_at?'Revoked':new Date(share.expires_at).getTime()<=Date.now()?'Expired':`Until ${new Date(share.expires_at).toLocaleString()}`}</span><a href={`/api/files/load-proof/${share.id}`} target="_blank">Open</a></div>)}</div><Pagination path={`/app/shipments/${id}`} query={{...detailPages,sharePage:undefined}} page={shareResult.page} pageCount={shareResult.pageCount} total={shareResult.total} pageParam="sharePage"/></>:null}</section>:null}
  {isParty?<section className="card"><h3>Internal note</h3><form action={`/api/shipments/${shipment.id}/note`} method="post" className="stack"><label htmlFor="internal-note">Note for shipment parties</label><textarea id="internal-note" name="note" required placeholder="Visible only to authorized shipment parties"/><button className="button secondary">Save note</button></form>{noteResult.total?<><div className="stack" style={{marginTop:14}}>{noteResult.items.map((note:any)=><div key={note.id}><strong>{note.author_name}</strong><div>{note.note}</div><div className="meta">{new Date(note.created_at).toLocaleString()}</div></div>)}</div><Pagination path={`/app/shipments/${id}`} query={{...detailPages,notePage:undefined}} page={noteResult.page} pageCount={noteResult.pageCount} total={noteResult.total} pageParam="notePage"/></>:null}</section>:null}
	  {canReviewBusiness?<section className="card"><h3>Rate {reviewTarget}</h3><p className="muted">Four- and five-star ratings publish now. Lower ratings stay private while Loadgistic investigates them.</p><form action={`/api/shipments/${shipment.id}/business-review`} method="post" className="stack"><fieldset className="star-rating"><legend>Rating</legend>{[1,2,3,4,5].map(value=><label key={value}><input type="radio" name="rating" value={value} required/><Star aria-hidden="true"/><span>{value}</span></label>)}</fieldset><div className="form-group"><label htmlFor="business-review-note">Review note (required for 1–3 stars)</label><textarea id="business-review-note" name="note" placeholder="Explain what happened so the administrator can investigate"/></div><button className="button icon-button-label"><Star aria-hidden="true"/>Submit review</button></form></section>:ownBusinessReview?.status==='PENDING'?<section className="card"><h3><ShieldAlert aria-hidden="true"/> Rating under review</h3><p className="muted">Your {ownBusinessReview.rating}-star rating is private while Loadgistic investigates it.</p></section>:null}
	  <section className="card"><h3>Tracking</h3><p><strong>{shipment.tracking_mode==='LOCATION_AND_STATUS'?'Approximate location + status':'Status timeline'}</strong></p><p className="meta">{shipment.tracking_mode==='LOCATION_AND_STATUS'?'The assigned provider must add a general area to each operational update. Exact coordinates are never shown.':'The assigned provider records timestamped status and note updates.'}</p>{canOpenCustomerTracking?<><div className="tracking-secret"><KeyRound aria-hidden="true"/><div><span>Secret load code</span><strong>{trackingAccessCode}</strong></div></div><Link href="/track" className="button secondary icon-button-label"><PackageSearch aria-hidden="true"/>Open customer tracking</Link></>:<p className="meta">Transport providers follow this load in the internal timeline shown on this page.</p>}{canManageTracking&&shipment.tracking_mode==='LOCATION_AND_STATUS'?<form action={`/api/shipments/${shipment.id}/tracking-mode`} method="post" style={{marginTop:10}}><input type="hidden" name="trackingMode" value="STATUS_ONLY"/><button className="button secondary" style={{width:'100%'}}>Change to status timeline</button></form>:null}</section>
	  {canOperate?<section className="card"><h3>Upload proof</h3><form action={`/api/shipments/${shipment.id}/proof`} method="post" encType="multipart/form-data" className="stack"><div className="form-group"><label htmlFor="proof-type">Proof type</label><select id="proof-type" name="proofType"><option value="LOADING">Loading proof</option><option value="DELIVERY">Delivery proof</option><option value="ISSUE">Issue proof</option></select></div><div className="form-group"><label htmlFor="proof-file"><Upload aria-hidden="true"/>Proof file</label><input id="proof-file" type="file" name="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></div><div className="form-group"><label htmlFor="proof-note">Proof note (optional)</label><input id="proof-note" name="note"/></div><button className="button secondary icon-button-label"><Upload aria-hidden="true"/>Upload proof</button></form></section>:null}
 </aside></div></div>;
}
