import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { getBusinessTrackingAccessCode, getDriverAccess, getShipmentForUser, listShipmentAssignmentVehicles, paginateResults } from '@/lib/repository.js';
import { nextStatuses } from '@/lib/domain.js';
import { priceDisplay } from '@/lib/ui';
import { PageHeader } from '@/components/page-header';
import { Pagination } from '@/components/pagination';
import { StatusPill } from '@/components/status-pill';
import { Flash } from '@/components/flash';
import { ShipmentTrackingControls } from '@/components/shipment-tracking-controls';
import { ShipmentPartiesForm } from '@/components/shipment-parties-form';
import { ShipmentProjectionRefresh } from '@/components/shipment-projection-refresh';
import {
  Boxes,
  Check,
  Eye,
  Handshake,
  KeyRound,
  MapPin,
  MessageSquare,
  PackageSearch,
  Phone,
  Save,
  Share2,
  ShieldAlert,
  Star,
  Truck,
  Upload,
  UserRound
} from 'lucide-react';

export default async function ShipmentDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); const access=getDriverAccess(user); const canNegotiate=access?.can_negotiate_loads!==false&&access?.can_contact_businesses!==false&&access?.can_browse_load_board!==false; const {id}=await params; const query=await searchParams; const shipment:any=getShipmentForUser(user,id); if(!shipment)notFound();
 const next=nextStatuses(shipment.service_mode,shipment.operational_status);
 const ownerOrganizationId=shipment.load_owner_organization_id||shipment.shipper_organization_id;
 const isParty=user.role==='ADMIN'||Boolean(user.organization_id&&[ownerOrganizationId,shipment.shipper_organization_id,shipment.receiver_organization_id,shipment.provider_organization_id].includes(user.organization_id))||Boolean(user.provider_profile_id&&shipment.provider_profile_id===user.provider_profile_id);
 const isAssignedCompanyDriver=user.role==='DRIVER'&&Boolean(user.organization_id)&&shipment.assigned_driver_user_id===user.id;
 const canPrepareAssignment=shipment.operational_status==='AGREED'&&['TRANSPORTER','DRIVER'].includes(user.role)&&access?.can_negotiate_loads!==false;
 const assignmentVehicles=canPrepareAssignment?listShipmentAssignmentVehicles(user,shipment.id):[];
 const canOperate=isParty&&(user.role==='ADMIN'||user.role==='TRANSPORTER'||(user.role==='DRIVER'&&(!user.organization_id||shipment.operational_status==='AGREED'||isAssignedCompanyDriver)));
 const directMatch=shipment.distribution_mode==='DIRECT_TO_PROVIDER'&&((['TRANSPORTER','DRIVER'].includes(user.role)&&user.organization_id&&shipment.provider_organization_id===user.organization_id)||(user.role==='DRIVER'&&user.provider_profile_id&&shipment.provider_profile_id===user.provider_profile_id));
 const isLoadOwner=shipment.service_mode==='FREIGHT'&&(user.role==='ADMIN'||ownerOrganizationId===user.organization_id);
 const canManageTracking=user.role==='ADMIN'||Boolean(['SHIPPER','RECEIVER'].includes(user.role)&&user.organization_id&&[ownerOrganizationId,shipment.shipper_organization_id,shipment.receiver_organization_id].includes(user.organization_id));
 const canOpenCustomerTracking=Boolean(['SHIPPER','RECEIVER'].includes(user.role)&&user.organization_id&&ownerOrganizationId===user.organization_id);
 const trackingStarted=['AGREED','ASSIGNED','IN_TRANSIT','ON_HOLD','ISSUE','DELIVERED','COMPLETED'].includes(shipment.operational_status);
 const trackingAccessCode=canOpenCustomerTracking?getBusinessTrackingAccessCode(user,shipment.id):null;
 const needsReceiverContact=shipment.service_mode==='FREIGHT'&&shipment.operational_status==='AGREED'&&(!shipment.receiver_first_name||!shipment.receiver_phone);
 const ownInterest=shipment.interests.find((interest:any)=>user.organization_id?interest.provider_organization_id===user.organization_id:interest.provider_profile_id===user.provider_profile_id);
 const activeLoadProof=shipment.load_proof_shares?.find((share:any)=>!share.revoked_at&&new Date(share.expires_at).getTime()>Date.now());
 const businessParties=[shipment.shipper_organization_id,shipment.receiver_organization_id].filter((value,index,all)=>Boolean(value)&&all.indexOf(value)===index);
 const ownBusinessReview=shipment.business_reviews.find((review:any)=>review.reviewer_organization_id===user.organization_id);
 const canReviewBusiness=shipment.operational_status==='COMPLETED'&&businessParties.length===2&&businessParties.includes(user.organization_id)&&!ownBusinessReview;
 const reviewTarget=user.organization_id===shipment.shipper_organization_id?shipment.receiver_name:shipment.shipper_name;
 const eventResult:any=paginateResults(shipment.events,{page:query.eventPage,pageSize:12});
 const proofResult:any=paginateResults(shipment.proofs,{page:query.proofPage,pageSize:10});
 const shareResult:any=paginateResults(shipment.load_proof_shares||[],{page:query.sharePage,pageSize:10});
 const detailPages={eventPage:query.eventPage,proofPage:query.proofPage,sharePage:query.sharePage};
 return <div className="page"><ShipmentProjectionRefresh/><PageHeader icon={PackageSearch} title={`${shipment.code} · ${shipment.title}`} subtitle={`${shipment.origin} → ${shipment.destination}`} action={<StatusPill status={shipment.operational_status}/>}/><Flash error={query.error} success={query.success}/>
 <div className="two-col"><div className="stack"><section className="card"><div className="split"><div><span className="meta">Price</span><h3>{priceDisplay(shipment)}</h3></div><div><span className="meta">Shipment owner</span><h3>{shipment.load_owner_name}</h3></div><div><span className="meta">Shipper</span><h3>{shipment.shipper_handle?<Link href={`/app/providers/${shipment.shipper_handle}`}>{shipment.shipper_name}</Link>:shipment.shipper_name||'Not selected'}</h3></div><div><span className="meta">Receiver</span><h3>{shipment.receiver_handle?<Link href={`/app/providers/${shipment.receiver_handle}`}>{shipment.receiver_name}</Link>:shipment.receiver_name||'Not selected'}</h3>{isParty&&shipment.receiver_first_name?<div className="meta">{shipment.receiver_first_name} · {shipment.receiver_phone}</div>:null}</div><div><span className="meta">Provider</span><h3>{shipment.provider_name||shipment.provider_profile_name||'Not assigned'}</h3></div>{shipment.assigned_vehicle_id?<><div><span className="meta">Assigned truck</span><h3>{shipment.assigned_vehicle_platform_number} · {shipment.assigned_vehicle_make} {shipment.assigned_vehicle_model}</h3><div className="meta">{shipment.assigned_vehicle_configuration}</div></div><div><span className="meta">Assigned Driver</span><h3>{shipment.assigned_driver_name}</h3></div></>:null}<div><span className="meta">Pick up before</span><h3>{shipment.pickup_date}</h3></div><div><span className="meta">Drop off before</span><h3>{shipment.delivery_date||'Not set'}</h3></div></div><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'20px 0'}}/><h3><Boxes aria-hidden="true"/>Shipment detail</h3><p>{shipment.cargo_description}</p><div className="meta">{shipment.vehicle_category||'Cargo configuration discussed directly'}{shipment.load_type?` · ${shipment.load_type==='FTL'?'Full Truckload (FTL)':'Partial Truckload (PTL)'}`:''}</div></section>
 {shipment.service_mode==='FREIGHT'?<section className="load-policy-banner"><span className="status">{shipment.load_type==='FTL'?'Full Truckload (FTL)':shipment.load_type==='PTL'?'Partial Truckload (PTL)':'Not specified'}</span><div><strong>{shipment.load_type==='FTL'?'Full truckload required':'Partial truckload is suitable'}</strong><span>{shipment.load_type==='FTL'?'This shipment needs a dedicated truck.':'This shipment can use available shared cargo space.'}</span></div></section>:null}
 <section className="card"><h2 className="panel-heading"><MapPin aria-hidden="true"/>{trackingStarted?'Tracking timeline':'Shipment activity'}</h2><ol className="timeline">{eventResult.items.map((event:any)=><li key={event.id}><strong>{event.event_type==='LOCATION'?'Location update':event.event_type==='TRACKING_MODE'?'Tracking preference changed':event.status.replaceAll('_',' ')}</strong><div>{event.note||'Status updated'}</div>{event.location_area?<div className="tracking-location-line"><strong>{event.location_area}</strong><span>{event.location_source==='DEVICE_OBSCURED'?`Approximate device area · ${event.location_precision_km} km privacy zone`:'Driver-declared general area'}</span></div>:null}<div className="meta">{event.actor_name||'Loadgistic'} · {new Date(event.created_at).toLocaleString()}</div></li>)}</ol><Pagination path={`/app/shipments/${id}`} query={{...detailPages,eventPage:undefined}} page={eventResult.page} pageCount={eventResult.pageCount} total={eventResult.total} pageParam="eventPage"/></section>
 {proofResult.total?<section className="card"><h2 className="panel-heading"><Upload aria-hidden="true"/>Proof</h2><div className="stack">{proofResult.items.map((proof:any)=><div className="proof-row" key={proof.id}><strong>{proof.proof_type} Proof</strong><div className="meta">Uploaded by {proof.uploaded_by_name} · {new Date(proof.created_at).toLocaleString()}</div><p>{proof.note}</p><a className="button secondary small" href={`/api/files/proof/${proof.id}`} target="_blank"><Eye aria-hidden="true"/>Open file</a></div>)}</div><Pagination path={`/app/shipments/${id}`} query={{...detailPages,proofPage:undefined}} page={proofResult.page} pageCount={proofResult.pageCount} total={proofResult.total} pageParam="proofPage"/></section>:null}
 </div>
 <aside className="stack">
	  {isLoadOwner&&shipment.operational_status==='AGREED'?<section className="card"><h3><UserRound aria-hidden="true"/>Shipment parties</h3><p className="muted">Set the shipper, receiver, and private receiver contact before truck assignment.</p><ShipmentPartiesForm shipmentId={shipment.id} ownerPartyRole={shipment.load_owner_party_role} receiverFirstName={shipment.receiver_first_name||''} receiverPhone={shipment.receiver_phone||''}/></section>:null}
	  {isLoadOwner&&shipment.operational_status==='AGREED'&&!shipment.assigned_vehicle_id?<section className="card tracking-setup-card"><div className="workflow-step-heading"><span>2</span><PackageSearch aria-hidden="true"/><div><h3>Tracking setup</h3><p>Choose what the Driver must update.</p></div></div><form action={`/api/shipments/${shipment.id}/tracking-mode`} method="post" className="stack"><div className="rich-choice-grid two"><label className="rich-choice"><input type="radio" name="trackingMode" value="STATUS_ONLY" defaultChecked={shipment.tracking_mode==='STATUS_ONLY'}/><Check aria-hidden="true"/><span><strong>Status only</strong><small>Loading through Complete</small></span></label><label className="rich-choice"><input type="radio" name="trackingMode" value="LOCATION_AND_STATUS" defaultChecked={shipment.tracking_mode==='LOCATION_AND_STATUS'}/><MapPin aria-hidden="true"/><span><strong>Automatic location + status</strong><small>Driver phone sends a private area</small></span></label></div><button className="button icon-button-label"><Save aria-hidden="true"/>Save tracking</button></form></section>:null}
	  {directMatch&&canNegotiate&&shipment.service_mode==='FREIGHT'&&shipment.commercial_status!=='AGREED'?<section className="card"><h3><Handshake aria-hidden="true"/>Direct request</h3><p className="muted">Accept after agreeing with the business.</p><form action={`/api/shipments/${shipment.id}/accept`} method="post"><button className="button" style={{width:'100%'}}><Check aria-hidden="true"/>Accept request</button></form></section>:null}
  {canPrepareAssignment?<section className="card shipment-assignment-card"><div className="workflow-step-heading"><span>1</span><Truck aria-hidden="true"/><div><h3>Choose truck</h3><p>The assigned Driver moves this Shipment.</p></div></div>{assignmentVehicles.length?<form action={`/api/shipments/${shipment.id}/vehicle`} method="post" className="stack"><div className="form-group"><label htmlFor="shipment-vehicle"><Truck aria-hidden="true"/>Truck and Driver</label><select id="shipment-vehicle" name="vehicleId" defaultValue={shipment.assigned_vehicle_id||''} required><option value="">Choose truck</option>{assignmentVehicles.map((vehicle:any)=><option key={vehicle.id} value={vehicle.id}>{vehicle.platform_number} · {vehicle.make} {vehicle.model} · {vehicle.assigned_driver_name}</option>)}</select></div><button className="button icon-button-label"><Save aria-hidden="true"/>Assign truck</button></form>:<div className="alert">Assign a Driver to an active truck in My Fleet first.</div>}</section>:null}
  {canOperate?<ShipmentTrackingControls shipmentId={shipment.id} trackingMode={shipment.tracking_mode} nextStatuses={next} needsReceiverContact={needsReceiverContact} needsShipmentVehicle={!shipment.assigned_vehicle_id||!shipment.assigned_driver_user_id} operationalStatus={shipment.operational_status} allowDeviceLocation={user.role==='DRIVER'&&shipment.assigned_driver_user_id===user.id} loadType={shipment.load_type}/>:null}
	  {['TRANSPORTER','DRIVER'].includes(user.role)&&shipment.load_contact_phone?<section className="card"><h3><Phone aria-hidden="true"/>Business contact</h3><a className="button secondary icon-button-label" href={`tel:${shipment.load_contact_phone}`}><Phone aria-hidden="true"/>Call {shipment.load_contact_phone}</a></section>:null}
	  {['TRANSPORTER','DRIVER'].includes(user.role)&&canNegotiate&&!isParty&&shipment.service_mode==='FREIGHT'&&shipment.operational_status==='POSTED'&&!shipment.interests.some((i:any)=>(user.organization_id?i.provider_organization_id===user.organization_id:i.provider_profile_id===user.provider_profile_id))?<section className="card"><h3><Handshake aria-hidden="true"/>Interested?</h3><p className="muted">Send one clear interest signal. Use the Business phone for discussion.</p><form action={`/api/shipments/${shipment.id}/interest`} method="post"><button className="button"><Handshake aria-hidden="true"/>Express interest</button></form></section>:null}
	  {['TRANSPORTER','DRIVER'].includes(user.role)&&canNegotiate&&ownInterest?<section className="card"><h3><KeyRound aria-hidden="true"/>Shipment proof</h3>{ownInterest.created_by_name?<p className="meta">Interest sent by {ownInterest.created_by_name}.</p>:null}{activeLoadProof?<><p className="muted">Private access ends {new Date(activeLoadProof.expires_at).toLocaleString()}.</p><a className="button secondary" href={`/api/files/load-proof/${activeLoadProof.id}`} target="_blank"><Eye aria-hidden="true"/>Open proof</a></>:ownInterest.proof_request_id?<p className="muted">Requested {new Date(ownInterest.proof_requested_at).toLocaleString()}.</p>:<><p className="muted">Ask for private shipment-size evidence.</p><form action={`/api/shipments/${shipment.id}/load-proof/request`} method="post"><button className="button secondary"><KeyRound aria-hidden="true"/>Request proof</button></form></>}</section>:null}
	  {isLoadOwner&&shipment.interests.length?<section className="card"><h3><Share2 aria-hidden="true"/>Share shipment proof</h3><p className="muted">One transporter. Temporary private access.</p><form action={`/api/shipments/${shipment.id}/load-proof/share`} method="post" encType="multipart/form-data" className="stack"><div className="form-group"><label htmlFor="load-proof-interest"><UserRound aria-hidden="true"/>Transporter</label><select id="load-proof-interest" name="interestId" required><option value="">Choose an interested transporter</option>{shipment.interests.map((interest:any)=><option value={interest.id} key={interest.id}>{interest.organization_name||interest.provider_name}{interest.created_by_name?` · ${interest.created_by_name}`:''}{interest.proof_request_id?' · Proof requested':''}</option>)}</select></div><div className="form-group"><label htmlFor="load-proof-file"><Upload aria-hidden="true"/>Shipment proof</label><input id="load-proof-file" name="file" type="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/></div><button className="button secondary"><Share2 aria-hidden="true"/>Share proof</button></form>{shareResult.total?<><div className="temporary-share-list">{shareResult.items.map((share:any)=><div key={share.id}><strong>{share.organization_name||share.provider_name}</strong><span>{share.revoked_at?'Revoked':new Date(share.expires_at).getTime()<=Date.now()?'Expired':`Until ${new Date(share.expires_at).toLocaleString()}`}</span><a href={`/api/files/load-proof/${share.id}`} target="_blank"><Eye aria-hidden="true"/>Open</a></div>)}</div><Pagination path={`/app/shipments/${id}`} query={{...detailPages,sharePage:undefined}} page={shareResult.page} pageCount={shareResult.pageCount} total={shareResult.total} pageParam="sharePage"/></>:null}</section>:null}
	  {canReviewBusiness?<section className="card"><h3><Star aria-hidden="true"/>Rate {reviewTarget}</h3><p className="muted">Four- and five-star ratings publish now. Lower ratings stay private while Loadgistic investigates them.</p><form action={`/api/shipments/${shipment.id}/business-review`} method="post" className="stack"><fieldset className="star-rating"><legend><Star aria-hidden="true"/>Rating</legend>{[1,2,3,4,5].map(value=><label key={value}><input type="radio" name="rating" value={value} required/><Star aria-hidden="true"/><span>{value}</span></label>)}</fieldset><div className="form-group"><label htmlFor="business-review-note"><MessageSquare aria-hidden="true"/>Review note <span className="meta">(required for 1–3)</span></label><textarea id="business-review-note" name="note" placeholder="Explain what happened so the administrator can investigate"/></div><button className="button icon-button-label"><Star aria-hidden="true"/>Submit review</button></form></section>:ownBusinessReview?.status==='PENDING'?<section className="card"><h3><ShieldAlert aria-hidden="true"/> Rating under review</h3><p className="muted">Your {ownBusinessReview.rating}-star rating is private while Loadgistic investigates it.</p></section>:null}
	  {trackingStarted?<section className="card"><h3><PackageSearch aria-hidden="true"/>Tracking</h3><p><strong>{shipment.tracking_mode==='LOCATION_AND_STATUS'?'Automatic location + status':'Status only'}</strong></p><p className="meta">{shipment.tracking_mode==='LOCATION_AND_STATUS'?'Assigned Driver phone sends a private area automatically.':'Timestamped shipment actions.'}</p>{canOpenCustomerTracking?<><div className="tracking-secret"><KeyRound aria-hidden="true"/><div><span>Secret shipment code</span><strong>{trackingAccessCode}</strong></div></div><Link href="/track" className="button secondary icon-button-label"><PackageSearch aria-hidden="true"/>Customer tracking</Link></>:<p className="meta">Providers use the Shipment timeline.</p>}{canManageTracking&&shipment.tracking_mode==='LOCATION_AND_STATUS'?<form action={`/api/shipments/${shipment.id}/tracking-mode`} method="post" style={{marginTop:10}}><input type="hidden" name="trackingMode" value="STATUS_ONLY"/><button className="button secondary" style={{width:'100%'}}><Save aria-hidden="true"/>Status only</button></form>:null}</section>:null}
 </aside></div></div>;
}
