import Link from 'next/link';
import { notFound } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { getShipmentForUser } from '@/lib/repository.js';
import { nextStatuses } from '@/lib/domain.js';
import { priceDisplay } from '@/lib/ui';
import { PageHeader } from '@/components/page-header';
import { StatusPill } from '@/components/status-pill';
import { Flash } from '@/components/flash';

export default async function ShipmentDetailPage({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); const {id}=await params; const query=await searchParams; const shipment:any=getShipmentForUser(user,id); if(!shipment)notFound();
 const next=nextStatuses(shipment.service_mode,shipment.operational_status);
 const canOperate=shipment.service_mode==='PARCEL'?['PARCEL','ADMIN'].includes(user.role):['TRANSPORTER','DRIVER','ADMIN'].includes(user.role);
 const directMatch=shipment.distribution_mode==='DIRECT_TO_PROVIDER'&&((user.role==='TRANSPORTER'&&shipment.provider_organization_id===user.organization_id)||(user.role==='DRIVER'&&shipment.provider_profile_id===user.provider_profile_id));
 return <div className="page"><PageHeader title={`${shipment.code} · ${shipment.title}`} subtitle={`${shipment.origin} → ${shipment.destination}`} action={<StatusPill status={shipment.operational_status}/>}/><Flash error={query.error} success={query.success}/>
 <div className="two-col"><div className="stack"><section className="card"><div className="split"><div><span className="meta">Service</span><h3>{shipment.service_mode==='PARCEL'?'Parcel Delivery':'Road Freight'}</h3></div><div><span className="meta">Price</span><h3>{priceDisplay(shipment)}</h3></div><div><span className="meta">Shipper</span><h3>{shipment.shipper_name}</h3></div><div><span className="meta">Receiver</span><h3>{shipment.receiver_name||'External / not selected'}</h3></div><div><span className="meta">Provider</span><h3>{shipment.provider_name||shipment.provider_profile_name||'Not assigned'}</h3></div><div><span className="meta">Pickup</span><h3>{shipment.pickup_date}</h3></div></div><hr style={{border:0,borderTop:'1px solid var(--line)',margin:'20px 0'}}/><h3>Cargo or package</h3><p>{shipment.cargo_description}</p><div className="meta">{shipment.package_count} package(s){shipment.estimated_weight?` · ${shipment.estimated_weight} kg`:''}{shipment.vehicle_category?` · ${shipment.vehicle_category}`:''}{shipment.load_type?` · ${shipment.load_type.replaceAll('_',' ')}`:''}</div></section>
 <section className="card"><h2 style={{fontSize:'1.4rem'}}>Timeline</h2><ol className="timeline">{shipment.events.map((event:any)=><li key={event.id}><strong>{event.status.replaceAll('_',' ')}</strong><div>{event.note||'Status updated'}</div><div className="meta">{event.actor_name||'Loadgistic'} · {new Date(event.created_at).toLocaleString()}</div></li>)}</ol></section>
 {shipment.proofs.length?<section className="card"><h2 style={{fontSize:'1.4rem'}}>Proof</h2><div className="stack">{shipment.proofs.map((proof:any)=><div className="card" key={proof.id}><strong>{proof.proof_type} Proof</strong><div className="meta">Uploaded by {proof.uploaded_by_name} · {new Date(proof.created_at).toLocaleString()}</div><p>{proof.note}</p><a className="button secondary small" href={`/api/files/proof/${proof.id}`} target="_blank">Open file</a></div>)}</div></section>:null}
 </div>
 <aside className="stack">
  {directMatch&&shipment.service_mode==='FREIGHT'&&shipment.commercial_status!=='AGREED'?<section className="card"><h3>Direct request</h3><p className="muted">Accept only after you agree directly with the business.</p><form action={`/api/shipments/${shipment.id}/accept`} method="post"><button className="button" style={{width:'100%'}}>Accept direct request</button></form></section>:null}
  {canOperate&&next.length?<section className="card"><h3>Next status</h3><p className="meta">Only valid next actions are shown.</p><div className="stack">{next.map((status:string)=><form action={`/api/shipments/${shipment.id}/status`} method="post" key={status}><input type="hidden" name="nextStatus" value={status}/><input name="note" placeholder={`Optional note for ${status.replaceAll('_',' ').toLowerCase()}`} style={{marginBottom:8}}/><button className="button secondary" style={{width:'100%'}}>{status.replaceAll('_',' ')}</button></form>)}</div></section>:null}
  {['TRANSPORTER','DRIVER'].includes(user.role)&&shipment.service_mode==='FREIGHT'&&!shipment.interests.some((i:any)=>(user.role==='TRANSPORTER'?i.provider_organization_id===user.organization_id:i.provider_profile_id===user.provider_profile_id))?<section className="card"><h3>Interested in this load?</h3><form action={`/api/shipments/${shipment.id}/interest`} method="post" className="stack"><textarea name="note" placeholder="Optional message to the business"/><button className="button">Express interest</button></form></section>:null}
  <section className="card"><h3>Internal note</h3><form action={`/api/shipments/${shipment.id}/note`} method="post" className="stack"><textarea name="note" required placeholder="Visible only to authorized shipment parties"/><button className="button secondary">Save note</button></form>{shipment.notes.length?<div className="stack" style={{marginTop:14}}>{shipment.notes.map((note:any)=><div key={note.id}><strong>{note.author_name}</strong><div>{note.note}</div><div className="meta">{new Date(note.created_at).toLocaleString()}</div></div>)}</div>:null}</section>
  {shipment.tracking_token?<section className="card"><h3>Tracking</h3><p className="meta">Tracking mode: {shipment.tracking_mode.replaceAll('_',' ')}</p><Link href={`/track/${shipment.tracking_token}`} className="button secondary" target="_blank">Open tracking page</Link></section>:null}
  {canOperate?<section className="card"><h3>Upload proof</h3><form action={`/api/shipments/${shipment.id}/proof`} method="post" encType="multipart/form-data" className="stack"><select name="proofType"><option value="LOADING">Loading Proof</option><option value="DELIVERY">Delivery Proof</option><option value="ISSUE">Issue Proof</option></select><input type="file" name="file" accept="image/jpeg,image/png,image/webp,application/pdf" required/><input name="note" placeholder="Optional proof note"/><button className="button secondary">Upload proof</button></form></section>:null}
 </aside></div></div>;
}
