import Link from 'next/link';
import { ArrowRight, Boxes, Factory, Gauge, Hammer, Leaf, MapPinned, Route, ShieldCheck, Truck, Warehouse } from 'lucide-react';
import { PublicHeader } from '@/components/public-header';
import { PublicCapacityFeed } from '@/components/public-capacity-feed';
import { listPublicCapacityCursor } from '@/lib/repository.js';

export const dynamic='force-dynamic';

export default function HomePage() {
  const initial=listPublicCapacityCursor({}, {pageSize:14});
  return <><PublicHeader/><main>
    <section className="producer-hero"><div className="producer-hero-shade"/><div className="container producer-hero-content"><span className="hero-kicker"><MapPinned aria-hidden="true"/>Road capacity already moving through Ethiopia</span><h1>Trade farther without carrying the full cost of an empty truck.</h1><p>Loadgistic makes existing freight capacity visible to the manufacturers, workshops, growers, processors, and producers taking the greatest risk to build local and regional trade.</p><div className="hero-actions"><Link className="button hero-primary" href="/capacity">Find available capacity<ArrowRight aria-hidden="true"/></Link><Link className="button hero-secondary" href="/apply?type=TRANSPORT_COMPANY">Publish your trucks<Truck aria-hidden="true"/></Link></div><div className="hero-trust-line"><span>No seeker account</span><span>Current radius and route signals</span><span>Provider pages built to earn trust</span></div></div></section>
    <section className="producer-strip"><div className="container producer-type-grid"><div className="producer-type"><Factory aria-hidden="true"/><span><strong>Manufacturers</strong><small>Reach inputs, buyers, and new regions.</small></span></div><div className="producer-type"><Hammer aria-hidden="true"/><span><strong>Workshops</strong><small>Move materials without owning a fleet.</small></span></div><div className="producer-type"><Leaf aria-hidden="true"/><span><strong>Growers</strong><small>Find capacity around harvest and market days.</small></span></div><div className="producer-type"><Warehouse aria-hidden="true"/><span><strong>Producers</strong><small>Build reliable local and regional lanes.</small></span></div></div></section>
    <section className="home-capacity-market"><div className="container"><div className="home-market-heading"><div><span className="section-kicker">Available now</span><h2>Start with the capacity market—not a registration form.</h2><p>Compare Empty and Partial trucks, see the provider behind each signal, and use the map only when it helps.</p></div><Link className="button secondary" href="/capacity">Open all filters<ArrowRight aria-hidden="true"/></Link></div><PublicCapacityFeed initial={initial} query={{q:'',status:'',geometry:''}}/></div></section>
    <section className="production-value-section"><div className="container value-band-grid"><div className="value-band-copy"><span className="section-kicker">Why this market matters</span><h2>One truck can unlock more than one business opportunity.</h2><p className="lede">A partially loaded truck, an empty return, a recurring route, or a permanent working area can lower the practical barrier between a small producer and a customer in another city. Loadgistic helps people discover that opportunity; the parties still confirm price, fit, documents, and terms directly.</p></div><div className="landing-icon-list"><div><Boxes aria-hidden="true"/><span><strong>Use partial cargo space</strong><small>Ask whether your freight can share existing capacity.</small></span></div><div><Route aria-hidden="true"/><span><strong>Follow recurring routes</strong><small>Find providers who repeatedly operate the lane you need.</small></span></div><div><Gauge aria-hidden="true"/><span><strong>See the signal type</strong><small>Current radius, current route, next trip, recurring route, and working area remain distinct.</small></span></div><div><ShieldCheck aria-hidden="true"/><span><strong>Check before agreeing</strong><small>Badges help you inspect evidence; they never replace your own due diligence.</small></span></div></div></div></section>
    <section className="public-purpose-band"><div className="container public-purpose-grid"><div><Factory aria-hidden="true"/><span><small>For capacity seekers</small><strong>Browse freely, then coordinate directly</strong><p>No seeker account and no public demand post. Contact the provider you choose and agree offline.</p></span></div><div><Truck aria-hidden="true"/><span><small>For transport providers</small><strong>Present the business behind every truck</strong><p>Publish capacity, build a branded provider page, record agreed shipments, and keep the operational history.</p></span></div></div></section>
  </main><footer className="footer"><div className="container footer-grid"><strong>Loadgistic</strong><span>Public road-freight capacity discovery and provider-owned tracking for Ethiopia.</span><Link href="/about">About</Link><Link href="/providers">Providers</Link><Link href="/track">Track shipment</Link></div></footer></>;
}
