import {useEffect,useRef,useState} from 'react';
import {Modal,Pressable,ScrollView,Text,View} from 'react-native';
import {useAccount} from '../session/provider';
import {useLanguage} from '../localization/provider';
import {Button,Copy,ErrorText,Title,palette} from './ui';
import {ExternalButton} from './public-details';
import {contentConsentForActor} from '../../../../src/lib/privacy/content-policy-intent.js';
export function ContentPolicyConsent(){
 const account=useAccount(),{t}=useLanguage(),actor=account.session?.user.id,[required,setRequired]=useState(false),[intent,setIntent]=useState<{actorId?:string;checked:boolean}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),epoch=useRef(0),checked=contentConsentForActor(intent,actor);
 useEffect(()=>{const operationEpoch=epoch,version=++operationEpoch.current;if(!actor)return;const request=account.request;void request('/api/mobile/account/policy').then(data=>{if(version!==operationEpoch.current)return;const value=data as {accepted:boolean};setIntent(null);setRequired(value.accepted!==true);setError('');}).catch(()=>{if(version===operationEpoch.current){setRequired(true);setError('The terms could not be loaded. Try again.');}});return()=>{operationEpoch.current++;};},[actor,account.request]);
 const accept=async()=>{if(busy||!checked)return;const version=epoch.current;setBusy(true);setError('');try{const data=await account.request('/api/mobile/account/policy',{version:'2026-10-09',accepted:true,actorId:actor}) as {accepted:boolean};if(!data.accepted)throw Error();if(version===epoch.current)setRequired(false);}catch{if(version===epoch.current)setError('The terms could not be accepted. Try again.');}finally{setBusy(false);}};
 return <Modal visible={Boolean(actor&&required)} transparent animationType="fade" onRequestClose={()=>undefined}><View style={{flex:1,backgroundColor:'rgba(23,44,70,.3)',padding:20,justifyContent:'center'}}><ScrollView accessibilityViewIsModal style={{maxWidth:480,width:'100%',maxHeight:'90%',flexGrow:0,alignSelf:'center',backgroundColor:'#fff',borderRadius:18}} contentContainerStyle={{padding:20,gap:14}}><Title message="Before you share"/><Copy message="Share accurate information you have permission to use. Do not post fraud, threats, harassment, hate, sexual content or anyone's private information without permission."/><Copy message="People can report content or block a transporter. Our team reviews reports and can remove content or restrict accounts."/><ExternalButton label={t('Terms')} url="https://loadgistic.com/terms"/><ExternalButton label={t('Privacy')} url="https://loadgistic.com/privacy"/><Pressable accessibilityRole="checkbox" aria-checked={checked} accessibilityState={{checked,disabled:busy}} disabled={busy} onPress={()=>setIntent({actorId:actor,checked:!checked})} style={{minHeight:48,flexDirection:'row',gap:10,alignItems:'center'}}><Text style={{fontSize:22,color:palette.teal}}>{checked?'☑':'☐'}</Text><Text style={{color:palette.ink,flex:1,lineHeight:22}}>{t('I agree to the Terms and content rules.')}</Text></Pressable><ErrorText message={error}/><Button message="Accept and continue" disabled={!checked} busy={busy} onPress={()=>void accept()}/><Button secondary message="Sign out" disabled={busy} onPress={()=>{void account.signOut().catch(()=>setError('Could not confirm sign out. Please try again.'));}}/><ExternalButton label={t('Delete account and data')} url="https://loadgistic.com/delete-account"/></ScrollView></View></Modal>;
}
