import {useState} from 'react';
import {Modal,Pressable,ScrollView,StyleSheet,Text,View} from 'react-native';
import {calendarDates,calendarDay,calendarPeriod,dateAllowed,dateOnly,shiftCalendar,todayDate,type CalendarView} from '../../../../src/lib/date-calendar';
import {useLanguage} from '../localization/provider';
import {AppIcon} from './app-icon';
import {palette} from './ui';
type Props={message:string;value:string;onChange:(date:string)=>void;min?:string;max?:string;disabled?:boolean;required?:boolean};
export function DatePicker({message,value,onChange,min='',max='',disabled=false,required=false}:Props){
 const {locale,t}=useLanguage(),[open,setOpen]=useState(false),[anchor,setAnchor]=useState(value||todayDate()),[view,setView]=useState<CalendarView>('week');
 function show(){setAnchor(dateOnly(value)?value:min&&min>todayDate()?min:todayDate());setView('week');setOpen(true);}
 return <View style={{gap:7}}><Text style={styles.label}>{t(message)}</Text><Pressable disabled={disabled} accessibilityRole="button" accessibilityLabel={`${t(message)}: ${dateOnly(value)?calendarDay(value,locale).label:t('Choose date')}`} onPress={show} style={styles.trigger}><AppIcon name="calendar" size={20} color={palette.teal}/><Text style={{flex:1,color:palette.ink}}>{dateOnly(value)?calendarDay(value,locale).label:t('Choose date')}</Text></Pressable>
  <Modal visible={open} transparent animationType="fade" onRequestClose={()=>setOpen(false)}><View style={styles.overlay}><Pressable style={StyleSheet.absoluteFill} accessibilityLabel={t('Close')} onPress={()=>setOpen(false)}/><ScrollView accessibilityViewIsModal style={styles.dialog} contentContainerStyle={styles.dialogContent} keyboardShouldPersistTaps="handled">
   <View style={styles.row}><Text style={styles.heading}>{t(message)}</Text><Pressable accessibilityRole="button" accessibilityLabel={t('Close')} onPress={()=>setOpen(false)} style={styles.control}><AppIcon name="close" size={22}/></Pressable></View>
   <View style={styles.row}>{(['week','month'] as const).map(mode=><Pressable key={mode} accessibilityRole="button" accessibilityState={{selected:view===mode}} onPress={()=>setView(mode)} style={[styles.viewButton,view===mode&&styles.selected]}><Text style={{color:view===mode?'#fff':palette.teal}}>{t(mode==='week'?'Week':'Month')}</Text></Pressable>)}</View>
   <View style={styles.row}><Pressable accessibilityRole="button" accessibilityLabel={t(view==='week'?'Previous week':'Previous month')} style={styles.control} onPress={()=>setAnchor(shiftCalendar(anchor,view,-1))}><AppIcon name="back" size={20}/></Pressable><Text style={styles.period}>{calendarPeriod(anchor,view,locale)}</Text><Pressable accessibilityRole="button" accessibilityLabel={t(view==='week'?'Next week':'Next month')} style={styles.control} onPress={()=>setAnchor(shiftCalendar(anchor,view,1))}><AppIcon name="next" size={20}/></Pressable></View>
   <View style={styles.grid}>{calendarDates(anchor,view).map(day=>{const info=calendarDay(day,locale),allowed=dateAllowed(day,min,max),selected=day===value;return <Pressable key={day} disabled={!allowed} accessibilityRole="button" accessibilityState={{selected,disabled:!allowed}} accessibilityLabel={`${info.label}${info.ethiopian?`, ${t('Ethiopian calendar')}: ${info.ethiopian.label}`:''}`} onPress={()=>{onChange(day);setOpen(false);}} style={[styles.day,selected&&styles.selected,!allowed&&{opacity:.3}]}><Text numberOfLines={1} style={[styles.weekday,selected&&styles.white]}>{info.weekday}</Text><Text style={[styles.number,selected&&styles.white]}>{info.day}</Text>{info.ethiopian&&<Text style={[styles.ethiopian,selected&&styles.white]}>{info.ethiopian.day}</Text>}</Pressable>;})}</View>
   {calendarDay(anchor,locale).ethiopian&&<Text style={styles.legend}>{t('Gregorian date above · Ethiopian date below')}</Text>}
   <View style={styles.row}><Pressable accessibilityRole="button" style={styles.control} onPress={()=>setAnchor(todayDate())}><Text style={styles.label}>{t('Today')}</Text></Pressable>{!required&&<Pressable accessibilityRole="button" style={styles.control} onPress={()=>{onChange('');setOpen(false);}}><Text style={styles.label}>{t('Clear date')}</Text></Pressable>}</View>
  </ScrollView></View></Modal>
 </View>;
}
const styles=StyleSheet.create({label:{color:palette.ink,fontWeight:'600'},trigger:{flexDirection:'row',alignItems:'center',gap:10,minHeight:50,borderWidth:1,borderColor:palette.border,borderRadius:12,padding:12},overlay:{flex:1,backgroundColor:'rgba(23,44,70,.22)',justifyContent:'center',padding:12},dialog:{backgroundColor:'#fff',borderRadius:20,width:'100%',maxWidth:540,maxHeight:'95%',flexGrow:0,alignSelf:'center'},dialogContent:{padding:12,gap:12},row:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:4},heading:{color:palette.ink,fontWeight:'700',fontSize:18,flex:1},control:{minHeight:44,minWidth:44,alignItems:'center',justifyContent:'center',paddingHorizontal:5},period:{flex:1,textAlign:'center',color:palette.ink,fontWeight:'600'},viewButton:{flex:1,alignItems:'center',borderRadius:10,padding:12,backgroundColor:'#eaf5f4'},grid:{flexDirection:'row',flexWrap:'wrap'},day:{width:'14.285714%',minHeight:68,justifyContent:'center',alignItems:'center',borderRadius:10,paddingVertical:5},selected:{backgroundColor:palette.teal},white:{color:'#fff'},weekday:{color:palette.muted,fontSize:10},number:{color:palette.ink,fontSize:19,fontWeight:'700'},ethiopian:{color:palette.teal,fontSize:12},legend:{fontSize:12,color:palette.muted,textAlign:'center'}});
