import { useRef,useState } from 'react';
import { Modal,Pressable,ScrollView,Text,View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { changeAvailability,changeSpace,type TruckFilters } from '../api/discovery';
import { captureCapacityLocation } from '../location/capture';
import { Button,Copy,ErrorText,palette,Title } from './ui';
import { PlacePicker } from './place-picker';
import { ConfigurationPicker,type Configuration } from './configuration-picker';
function Options({label,value,choices,onChange}:{label:string;value:string;choices:[string,string][];onChange:(value:string)=>void}) {
 return <View style={{gap:8}}><Text style={{fontWeight:'700',color:palette.ink}}>{label}</Text><View style={{flexDirection:'row',flexWrap:'wrap',gap:8}}>{choices.map(([id,title])=><Pressable key={id} accessibilityRole="radio" accessibilityState={{checked:id===value}} onPress={()=>onChange(id)} style={{minHeight:46,borderRadius:12,padding:12,borderWidth:1,borderColor:id===value?palette.teal:palette.border,backgroundColor:id===value?'#eaf5f4':'#fff'}}><Text style={{color:palette.ink}}>{title}</Text></Pressable>)}</View></View>;
}
function Documents({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:[string,string][]}) {
 const selected=value?value.split(','):[];
 return <View style={{gap:8}}><Text style={{fontWeight:'700',color:palette.ink}}>{label}</Text>{options.map(([id,title])=><Pressable key={id} accessibilityRole="checkbox" accessibilityState={{checked:selected.includes(id)}} onPress={()=>onChange((selected.includes(id)?selected.filter(item=>item!==id):[...selected,id]).join(','))} style={{minHeight:46,padding:12,borderRadius:12,borderWidth:1,borderColor:selected.includes(id)?palette.teal:palette.border}}><Text style={{color:palette.ink}}>{selected.includes(id)?'☑':'☐'} {title}</Text></Pressable>)}</View>;
}
const radii:[string,string][]=['5','10','25','50','100','200','300'].map(radius=>[radius,`${radius} km`]);
export function DiscoveryFilters({initial,configurations,onApply,onClose}:{initial:TruckFilters;configurations:Configuration[];onApply:(filters:TruckFilters)=>void;onClose:()=>void}) {
 const [draft,setDraft]=useState(initial),[busy,setBusy]=useState(false),[error,setError]=useState(''),epoch=useRef(0);
 const set=(key:keyof TruckFilters,value:string)=>setDraft(d=>({...d,[key]:value}));
 const cancel=()=>{epoch.current++;onClose();};
 const nearby=async()=>{const id=++epoch.current;setBusy(true);setError('');try{const fix=await captureCapacityLocation(5);if(id===epoch.current)setDraft(d=>({...d,truckCityPlaceRef:'',truckCityLabel:'',truckLocationRadiusKm:'',nearLat:String(fix.approximateLat),nearLng:String(fix.approximateLng),nearRadiusKm:d.nearRadiusKm||'50'}));}catch(e){if(id===epoch.current)setError(e instanceof Error?e.message:'Could not find your location.');}finally{if(id===epoch.current)setBusy(false);}};
 return <Modal transparent animationType="slide" onRequestClose={cancel}><SafeAreaView style={{flex:1,backgroundColor:'rgba(12,114,117,0.10)',padding:12}}><View style={{flex:1,backgroundColor:'#fff',borderRadius:20,borderWidth:1,borderColor:palette.border,overflow:'hidden'}}><View style={{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:16}}><Title message={"Truck filters"}/><Button secondary message="Cancel" onPress={cancel}/></View><ScrollView keyboardShouldPersistTaps="handled" contentContainerStyle={{padding:18,gap:24}}>
 <Options label="Space needed" value={draft.loadType||''} choices={[["","Any"],["FTL","Full truck"],["PTL","Shared space"]]} onChange={value=>setDraft(d=>changeSpace(d,value as TruckFilters['loadType']))}/>
 <Options label="Availability" value={draft.status||''} choices={[["","Empty or Partial"],["EMPTY","Empty"],["PARTIAL","Partial"]]} onChange={value=>setDraft(d=>changeAvailability(d,value as TruckFilters['status']))}/>
 <View style={{gap:8}}><Text style={{color:palette.ink,fontWeight:'700'}}>Truck configuration</Text><ConfigurationPicker value={draft.vehicleCategory||''} options={configurations} onChange={value=>set('vehicleCategory',value)} label="Choose truck configuration"/>{!!draft.vehicleCategory&&<Button secondary message="Any configuration" onPress={()=>set('vehicleCategory','')}/>}</View>
 <View style={{gap:10}}><PlacePicker label="Truck in or near a city" value={{placeRef:draft.truckCityPlaceRef||'',label:draft.truckCityLabel||''}} onChange={place=>{epoch.current++;setBusy(false);setDraft(d=>({...d,truckCityPlaceRef:place.placeRef,truckCityLabel:place.label,truckLocationRadiusKm:d.truckLocationRadiusKm||'50',nearLat:'',nearLng:'',nearRadiusKm:''}));}}/>{!!draft.truckCityPlaceRef&&<><Options label="Distance from city" value={draft.truckLocationRadiusKm||'50'} choices={radii} onChange={value=>set('truckLocationRadiusKm',value)}/><Button secondary message="Remove truck city" onPress={()=>setDraft(d=>({...d,truckCityPlaceRef:'',truckCityLabel:'',truckLocationRadiusKm:''}))}/></>}<Button secondary label={draft.nearLat?'Update my approximate area':'Use my approximate area'} busy={busy} onPress={()=>void nearby()}/>{!!draft.nearLat&&<><Options label="Distance from my area" value={draft.nearRadiusKm||'50'} choices={['5','10','20','50','100'].map(radius=>[radius,`${radius} km`])} onChange={value=>set('nearRadiusKm',value)}/><Button secondary message="Remove my area" onPress={()=>setDraft(d=>({...d,nearLat:'',nearLng:'',nearRadiusKm:''}))}/></>}<Copy message={"Matches reported truck locations, allowing for their location accuracy."}/><ErrorText message={error}/></View>
 {(['origin','destination'] as const).map(kind=><View key={kind} style={{gap:10}}><PlacePicker label={kind==='origin'?'Shipment origin':'Shipment destination'} value={{placeRef:draft[`${kind}PlaceRef`]||'',label:draft[`${kind}Label`]||''}} onChange={place=>setDraft(d=>({...d,[`${kind}PlaceRef`]:place.placeRef,[`${kind}Label`]:place.label,[`${kind}RadiusKm`]:d[`${kind}RadiusKm`]||'50'}))}/>{!!draft[`${kind}PlaceRef`]&&<><Options label="Route distance tolerance" value={draft[`${kind}RadiusKm`]||'50'} choices={radii} onChange={value=>set(`${kind}RadiusKm`,value)}/><Button secondary label={`Remove ${kind}`} onPress={()=>setDraft(d=>({...d,[`${kind}PlaceRef`]:'',[`${kind}Label`]:'',[`${kind}RadiusKm`]:''}))}/></>}</View>)}
 {!!(draft.originPlaceRef||draft.destinationPlaceRef)&&<Options label="Route direction" value={draft.directionMode||'DIRECT'} choices={[["DIRECT","In this direction"],["EITHER","Either direction"]]} onChange={value=>set('directionMode',value)}/>}
 <Options label="Stops" value={draft.stopOption||''} choices={[["","Any"],["MULTI_PICK","Multiple pickups"],["MULTI_DROP","Multiple deliveries"]]} onChange={value=>set('stopOption',value)}/>
 <Options label="Capacity updated" value={draft.freshness||''} choices={[["","Any time"],["FRESH","Within 12 hours"],["UPDATE_NEEDED","Over 12 hours ago"]]} onChange={value=>set('freshness',value)}/>
 <Copy message={"Reviewed documents: matches every document you select. Review applies to that document, not a service guarantee."}/>
 <Documents label="Transporter documents" value={draft.ownerDocs||''} onChange={value=>set('ownerDocs',value)} options={[["IDENTITY","National ID"],["BUSINESS_LICENSE","Business license"],["BUSINESS_ADDRESS","Business address"]]}/>
 <Documents label="Driver documents" value={draft.driverDocs||''} onChange={value=>set('driverDocs',value)} options={[["IDENTITY","National ID"],["DRIVER_IDENTITY","Driver license"]]}/>
 <Documents label="Truck documents" value={draft.truckDocs||''} onChange={value=>set('truckDocs',value)} options={[["VEHICLE_OWNERSHIP","Truck ownership"],["VEHICLE_AUTHORIZATION","Permission to use truck"]]}/>
 <Button secondary message="Reset truck filters" onPress={()=>{epoch.current++;setBusy(false);setError('');setDraft({});}}/>
 </ScrollView><View style={{padding:16,borderTopWidth:1,borderColor:palette.border}}><Button message="Show matching trucks" disabled={busy} onPress={()=>{epoch.current++;onApply(draft);}}/></View></View></SafeAreaView></Modal>;
}
