import { useRef, useState } from 'react';
import { Alert, Switch, View } from 'react-native';
import { useAccount } from '../session/provider';
import {useLanguage} from '../localization/provider';
import { Card, Title, Copy, Field, Button, ErrorText } from './ui';
import { ConfigurationPicker, type Configuration } from './configuration-picker';
export type ManagedTruck = { id: string; make: string; model: string; plate: string; configuration: string; image: string; driver: string | null; interchangeable: boolean; supported: string[];useBasis?:'OWNED'|'PERMISSION'|null };
export function TruckControls({ truck, configurations, reload,singleTruck=false }: { truck: ManagedTruck; configurations: Configuration[]; reload: () => Promise<void>;singleTruck?:boolean }) {
 const {t}=useLanguage();
 const account = useAccount(), lock = useRef(false), [editing, setEditing] = useState(false), [make, setMake] = useState(truck.make), [model, setModel] = useState(truck.model), [plate, setPlate] = useState(truck.plate), [configuration, setConfiguration] = useState(truck.configuration), [error, setError] = useState(''), [busy, setBusy] = useState(false);
 const [useBasis,setUseBasis]=useState(truck.useBasis||'');
 async function save(action: 'EDIT_TRUCK' | 'TRAILER') { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { await account.request('/api/mobile/fleet', action === 'TRAILER' ? { action, vehicleId: truck.id, cargoConfiguration: configuration } : { action, vehicleId: truck.id, make, model, plate, cargoConfiguration: configuration,...(singleTruck?{useBasis}:{}) }); await reload(); setEditing(false); } catch (error) { setError(error instanceof Error ? error.message : 'Could not confirm the change. Refresh before retrying.'); } finally { lock.current = false; setBusy(false); } }
 return <><Button secondary label={editing ? t('Close truck editor') : singleTruck?t('Ownership or permission'):t('Edit truck')} disabled={busy} onPress={() => setEditing(value => !value)} />{editing && <View style={{ gap: 12 }}>{singleTruck?<><Copy message="How do you use this truck?"/><Button secondary={useBasis!=='OWNED'} message="I own this truck" busy={busy} onPress={()=>setUseBasis('OWNED')}/><Button secondary={useBasis!=='PERMISSION'} message="I rent it or have the owner's permission" busy={busy} onPress={()=>setUseBasis('PERMISSION')}/></>:<><Field message="Make" value={make} onChangeText={setMake} editable={!busy} /><Field message="Model" value={model} onChangeText={setModel} editable={!busy} /><Field message="Plate" value={plate} onChangeText={setPlate} editable={!busy} /></>}{(!singleTruck||truck.interchangeable)&&<ConfigurationPicker value={configuration} options={configurations.filter(item => truck.interchangeable ? truck.supported.includes(item.name) : !item.name.startsWith('Tractor + '))} onChange={setConfiguration} disabled={busy} />}<ErrorText message={error} /><Button message="Save truck details" busy={busy} disabled={singleTruck&&!useBasis} onPress={() => { void save('EDIT_TRUCK'); }} />{truck.interchangeable && <><Copy message={"Only the currently attached trailer is shown in capacity searches."}/><Button secondary message="Update attached trailer" busy={busy} onPress={() => { void save('TRAILER'); }} /></>}</View>}<VehicleLifecycle id={truck.id} reload={reload} /></>;
}
export function VehicleLifecycle({ id, retired = false, reload }: { id: string; retired?: boolean; reload: () => Promise<void> }) {
 const {t}=useLanguage();
 const [confirmed,setConfirmed]=useState(false);
 const account = useAccount(), lock = useRef(false), [open, setOpen] = useState(false), [reason, setReason] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState('');
 async function save() { if (lock.current||!confirmed) return; lock.current = true; setBusy(true); setError(''); try { await account.request('/api/mobile/fleet', { action: 'LIFECYCLE', vehicleId: id, active: retired, reason, confirm: true }); await reload(); setOpen(false);setConfirmed(false); } catch (error) { setError(error instanceof Error ? error.message : 'Could not confirm this change.'); } finally { lock.current = false; setBusy(false); } }
 const label = retired ? 'Restore truck' : 'Retire truck';
 return <View style={{ gap: 10 }}><Button secondary label={t(label)} disabled={busy} onPress={() => {setConfirmed(false);setOpen(value => !value);}} />{open && <><Copy>{retired ? 'Restore the truck, then assign a driver and publish fresh capacity.' : 'Remove the truck from active work while retaining its history. Active Tracking must be resolved first.'}</Copy><Field message="Reason for truck change" value={reason} onChangeText={setReason} maxLength={500} editable={!busy} /><ErrorText message={error} /><View style={{flexDirection:'row',alignItems:'center',gap:10}}><Switch accessibilityLabel={t('I confirm this truck change.')} value={confirmed} onValueChange={setConfirmed} disabled={busy}/><View style={{flex:1}}><Copy message="I confirm this truck change."/></View></View><Button message="Confirm" busy={busy} disabled={reason.trim().length < 5||!confirmed} onPress={() => {void save();}} /></>}</View>;
}
export function DriverContact({ driver, reload }: { driver: { id: string; name: string; phone: string }; reload: () => Promise<void> }) {
 const account = useAccount(), lock = useRef(false), [open, setOpen] = useState(false), [name, setName] = useState(driver.name), [phone, setPhone] = useState(driver.phone), [busy, setBusy] = useState(false), [error, setError] = useState('');
 async function save(remove: boolean) { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { await account.request('/api/mobile/fleet', remove ? { action: 'REMOVE_DRIVER', driverId: driver.id, confirm: true } : { action: 'DRIVER_CONTACT', driverId: driver.id, name, phone }); await reload(); setOpen(false); } catch (error) { setError(error instanceof Error ? error.message : 'Could not confirm the driver change.'); } finally { lock.current = false; setBusy(false); } }
 return <View style={{ gap: 10 }}><Button secondary message="Driver contact and access" disabled={busy} onPress={() => setOpen(value => !value)} />{open && <><Field message="Driver name" value={name} onChangeText={setName} editable={!busy} /><Field message="Driver phone" value={phone} onChangeText={setPhone} keyboardType="phone-pad" editable={!busy} /><ErrorText message={error} /><Button message="Save driver contact" busy={busy} onPress={() => { void save(false); }} /><Button secondary message="Remove driver from fleet" busy={busy} onPress={() => Alert.alert('Remove this driver?', 'Their assignments and fleet access will end. Past records are retained.', [{ text: 'Keep driver', style: 'cancel' }, { text: 'Remove driver', style: 'destructive', onPress: () => { void save(true); } }])} /></>}</View>;
}
export function TrailerSetup({ configuration, configurations, supported, onChange, disabled }: { configuration: string; configurations: Configuration[]; supported: string[]; onChange: (items: string[]) => void; disabled: boolean }) {
 return <View style={{ gap: 10 }}><Copy message={"Choose compatible trailers. The attached trailer always stays selected."}/>{configurations.filter(item => item.name.startsWith('Tractor + ')).map(item => <View key={item.name} style={{ flexDirection: 'row', gap: 10, alignItems: 'center' }}><Switch accessibilityLabel={`Compatible ${item.name}`} value={supported.includes(item.name) || item.name === configuration} disabled={disabled || item.name === configuration} onValueChange={value => onChange(value ? [...new Set([...supported, item.name])] : supported.filter(name => name !== item.name))} /><View style={{ flex: 1 }}><Copy>{item.name}</Copy></View></View>)}</View>;
}
export function FleetInvitation({ item, reload }: { item: { id: string; name: string; email: string; expiresAt: string; sentAt: string | null }; reload: () => Promise<void> }) {
 const account = useAccount(), lock = useRef(false), [busy, setBusy] = useState(false), [message, setMessage] = useState(''), [error, setError] = useState('');
 async function save(operation: 'SEND' | 'CANCEL') { if (lock.current) return; lock.current = true; setBusy(true); setError(''); try { const result = await account.request('/api/mobile/fleet', { action: 'INVITATION', invitationId: item.id, operation }) as { delivery?: string }; setMessage(result.delivery === 'sent' ? 'Invitation email sent.' : result.delivery === 'recent' ? 'An invitation was sent recently. Try again later.' : result.delivery === 'failed' ? 'Email delivery failed. The invitation is retained; you can retry.' : 'Invitation cancelled.'); await reload(); } catch (error) { setError(error instanceof Error ? error.message : 'Could not confirm this change.'); } finally { lock.current = false; setBusy(false); } }
 return <Card><Title>{item.name}</Title><Copy>{item.email}</Copy><Copy>Invitation expires {new Date(item.expiresAt).toLocaleDateString()}</Copy><ErrorText message={error} />{!!message && <Copy>{message}</Copy>}<Button secondary message="Send invitation email" busy={busy} onPress={() => { void save('SEND'); }} /><Button secondary message="Cancel invitation" busy={busy} onPress={() => Alert.alert('Cancel invitation?', 'This driver will no longer be able to accept it.', [{ text: 'Keep invitation', style: 'cancel' }, { text: 'Cancel invitation', onPress: () => { void save('CANCEL'); } }])} /></Card>;
}
