import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View, type TextInputProps,type ScrollViewProps } from 'react-native';
import type { PropsWithChildren } from 'react';
import { useLanguage } from '../localization/provider';
type AppCopy=PropsWithChildren<{message?:string}>;
type Label=({label:string;message?:never}|{message:string;label?:never});
export const palette = { ink: '#172c46', teal: '#0c7275', muted: '#526875', border: '#cbdadb' };
export function Page({ children,embedded=false,...scroll }: PropsWithChildren<{embedded?:boolean}&Pick<ScrollViewProps,'onLayout'|'onScroll'|'scrollEventThrottle'>>) { return embedded?<View style={{gap:16}}>{children}</View>:<ScrollView {...scroll} keyboardShouldPersistTaps="handled" contentContainerStyle={styles.page}>{children}</ScrollView>; }
export function Title({ children,message }: AppCopy) { const {t}=useLanguage();return <Text style={styles.title}>{message===undefined?children:t(message)}</Text>; }
export function Copy({ children,message }: AppCopy) { const {t}=useLanguage();return <Text style={styles.copy}>{message===undefined?children:t(message)}</Text>; }
export function Card({ children }: PropsWithChildren) { return <View style={styles.card}>{children}</View>; }
export function Field({ label,message, ...props }: TextInputProps & Label) { const {t}=useLanguage();const text=message===undefined?label:t(message);return <View style={styles.field}><Text style={styles.label}>{text}</Text><TextInput {...props} accessibilityLabel={text} style={[styles.input, props.style]} /></View>; }
export function Button({ label,message, onPress, busy = false, disabled = false, secondary = false }: Label & { onPress: () => void; busy?: boolean; disabled?: boolean; secondary?: boolean }) { const {t}=useLanguage();const text=message===undefined?label:t(message);return <Pressable accessibilityRole="button" accessibilityState={{ disabled: busy || disabled, busy }} disabled={busy || disabled} onPress={onPress} style={[styles.button, disabled && { opacity: 0.5 }, secondary && styles.secondary]}>{busy ? <ActivityIndicator color={secondary ? palette.teal : '#fff'} /> : <Text style={[styles.buttonText, secondary && { color: palette.teal }]}>{text}</Text>}</Pressable>; }
export function ErrorText({ message }: { message: string }) { return message ? <Text accessibilityRole="alert" style={styles.error}>{message}</Text> : null; }
const styles = StyleSheet.create({ page: { padding: 20, gap: 16, paddingBottom: 40, flexGrow: 1, backgroundColor: '#fff' }, title: { fontSize: 25, lineHeight: 32, fontWeight: '700', color: palette.ink }, copy: { fontSize: 15, lineHeight: 23, color: palette.muted }, card: { borderWidth: 1, borderColor: palette.border, padding: 16, borderRadius: 16, gap: 9 }, field: { gap: 7 }, label: { color: palette.ink, fontWeight: '600' }, input: { minHeight: 50, borderWidth: 1, borderColor: palette.border, borderRadius: 12, padding: 12, fontSize: 16, color: palette.ink }, button: { minHeight: 50, padding: 14, backgroundColor: palette.teal, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, secondary: { backgroundColor: '#eaf5f4' }, buttonText: { color: '#fff', fontSize: 16, fontWeight: '700' }, error: { color: '#9d2525', lineHeight: 22 } });
