'use client';
import React from 'react';
import {contentBlocks,changeContentBlock} from '@/lib/content-blocks.js';
import {Text,useTranslation} from './localization';
const key='loadgistic.blocked-providers.v1',event='loadgistic-blocks-changed';
export function useBlockedProviders(){
 const [blocked,setBlocked]=React.useState([] as string[]);
 React.useEffect(()=>{const read=()=>{try{setBlocked(contentBlocks(window.localStorage.getItem(key)));}catch{setBlocked([]);}};read();window.addEventListener(event,read);window.addEventListener('storage',read);return()=>{window.removeEventListener(event,read);window.removeEventListener('storage',read);};},[]);
 return {blocked,set:(handle:string,value:boolean)=>{const next=changeContentBlock(contentBlocks(window.localStorage.getItem(key)),handle,value);window.localStorage.setItem(key,JSON.stringify(next));window.dispatchEvent(new Event(event));}};
}
export function BlockedProviders(){const {t}=useTranslation();const prefs=useBlockedProviders(),[error,setError]=React.useState('');return <div className="stack"><h2><Text message="Blocked transporters"/></h2><p><Text message="Blocks apply to this device. Unblocking restores matching profiles and trucks."/></p>{!prefs.blocked.length?<p><Text message="No blocked transporters."/></p>:prefs.blocked.map((handle:string)=><div key={handle} className="button-row"><span>@{handle}</span><button className="button secondary small" onClick={()=>{try{prefs.set(handle,false);setError('');}catch{setError('Your preference could not be saved. Try again.');}}}><Text message="Unblock transporter"/></button></div>)}{error?<p role="alert">{t(error)}</p>:null}</div>}
export function ContentSafety({handle,reviewId,children}:{handle:string;reviewId?:string;children?:React.ReactNode}){
 const {t}=useTranslation();
 const prefs=useBlockedProviders(),isBlocked=prefs.blocked.includes(handle),[open,setOpen]=React.useState(false),[detail,setDetail]=React.useState(''),[category,setCategory]=React.useState(reviewId?'REVIEW':'PROFILE'),[busy,setBusy]=React.useState(false),[sent,setSent]=React.useState(false),[error,setError]=React.useState('');const lock=React.useRef(false);
 const dialog=React.useRef(null as HTMLDialogElement|null);
 React.useEffect(()=>{const element=dialog.current;if(open&&element&&!element.open)element.showModal();return()=>{if(element?.open)element.close();};},[open]);
 async function report(){if(lock.current)return;lock.current=true;setBusy(true);setError('');try{
  const storageKey='loadgistic.content-reporter.v1';let reporter=window.localStorage.getItem(storageKey);if(!reporter){reporter=crypto.randomUUID();window.localStorage.setItem(storageKey,reporter);}
  const response=await fetch('/api/mobile/public/content-report',{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json'},body:JSON.stringify({handle,reporter,category,detail,...(reviewId?{reviewId}:{})})});const data=await response.json();if(!response.ok||data.recorded!==true)throw Error(data.error?.message||'Your report could not be sent. Try again.');setSent(true);
 }catch(caught){setError(caught instanceof Error?caught.message:'Your report could not be sent. Try again.');}finally{lock.current=false;setBusy(false);}}
 return <>{isBlocked?<section className="card stack"><h2><Text message="Transporter blocked"/></h2><p><Text message="This profile and its trucks are hidden on this device. You can unblock it at any time."/></p></section>:children}
 <div className="button-row container content-safety-actions"><button type="button" className="button secondary small" onClick={()=>{setOpen(true);setSent(false);setError('');}}><Text message={reviewId?'Report review':'Report content'}/></button>{!reviewId?<button type="button" className="button secondary small" onClick={()=>{try{prefs.set(handle,!isBlocked);setError('');}catch{setError('Your preference could not be saved. Try again.');}}}><Text message={isBlocked?'Unblock transporter':'Block transporter'}/></button>:null}</div>
 {open?<dialog ref={dialog} className="content-report-dialog" onCancel={event=>{if(busy)event.preventDefault();else setOpen(false);}} style={{width:'calc(100% - 32px)',maxWidth:480,border:0,borderRadius:18,padding:0}}><section role="dialog" aria-modal="true" aria-labelledby="report-title" className="card stack" style={{maxWidth:480,width:'100%',maxHeight:'90dvh',overflowY:'auto'}}><h2 id="report-title"><Text message="Report content"/></h2>{sent?<p role="status"><Text message="Report received. Our team will review the content."/></p>:<form className="stack" onSubmit={e=>{e.preventDefault();void report();}}>{reviewId?null:<label><Text message="What are you reporting?"/><select value={category} disabled={busy} onChange={e=>setCategory(e.target.value)}><option value="PROFILE"><Text message="Profile"/></option><option value="PICTURE"><Text message="Picture"/></option><option value="REVIEW"><Text message="Review"/></option><option value="OTHER"><Text message="Other"/></option></select></label>}<label><Text message="Tell us what needs attention"/><textarea value={detail} onChange={e=>setDetail(e.target.value)} minLength={5} maxLength={1000} required disabled={busy}/></label><p className="meta"><Text message="Do not include passwords, tracking codes or private documents."/></p><button className="button" disabled={busy}><Text message="Send report"/></button></form>}<button className="button secondary" disabled={busy} onClick={()=>setOpen(false)}><Text message="Close"/></button>{error?<p role="alert">{t(error)}</p>:null}</section></dialog>:error?<p role="alert">{t(error)}</p>:null}
 </>;
}
