'use client';
import React from 'react';
import Link from 'next/link';
import {Text} from './localization';
import {contentConsentForActor} from '@/lib/privacy/content-policy-intent.js';
export function ContentPolicyConsent({actorId}:{actorId:string}){
 const [required,setRequired]=React.useState(false),[intent,setIntent]=React.useState(null as {actorId:string;checked:boolean}|null),[busy,setBusy]=React.useState(false),[error,setError]=React.useState('');const dialog=React.useRef(null as HTMLDialogElement|null),checked=contentConsentForActor(intent,actorId),currentActor=React.useRef(actorId);currentActor.current=actorId;
 const load=async()=>{try{const response=await fetch('/api/account/policy',{cache:'no-store',signal:AbortSignal.timeout(20000)});const data=await response.json();if(!response.ok||typeof data.accepted!=='boolean'||data.actorId!==actorId)throw Error();if(currentActor.current!==actorId)return;setRequired(!data.accepted);setError('');}catch{if(currentActor.current===actorId)setError('The terms could not be loaded. Try again.');}};
 React.useEffect(()=>{void load();},[actorId]);
 React.useEffect(()=>{const element=dialog.current;if(required&&element&&!element.open)element.showModal();return()=>{if(element?.open)element.close();};},[required]);
 async function accept(){if(busy||!checked)return;setBusy(true);setError('');try{const response=await fetch('/api/account/policy',{method:'POST',signal:AbortSignal.timeout(20000),headers:{'Content-Type':'application/json'},body:JSON.stringify({version:'2026-10-09',accepted:true,actorId})});const data=await response.json();if(!response.ok||data.accepted!==true)throw Error();if(currentActor.current===actorId)setRequired(false);}catch{if(currentActor.current===actorId)setError('The terms could not be accepted. Try again.');}finally{setBusy(false);}}
 return <>{error&&!required?<p role="alert">{error} <button className="button secondary small" onClick={()=>void load()}><Text message="Try again"/></button></p>:null}{required?<dialog ref={dialog} onCancel={event=>event.preventDefault()} style={{width:'calc(100% - 32px)',maxWidth:480,border:0,borderRadius:18,padding:24}}><div className="stack"><h2><Text message="Before you share"/></h2><p><Text message="Share accurate information you have permission to use. Do not post fraud, threats, harassment, hate, sexual content or anyone's private information without permission."/></p><p><Text message="People can report content or block a transporter. Our team reviews reports and can remove content or restrict accounts."/></p><div className="button-row"><Link href="/terms" target="_blank"><Text message="Terms"/></Link><Link href="/privacy" target="_blank"><Text message="Privacy"/></Link></div><label><input type="checkbox" checked={checked} onChange={event=>setIntent({actorId,checked:event.target.checked})} disabled={busy}/><Text message="I agree to the Terms and content rules."/></label><button className="button" disabled={busy||!checked} onClick={()=>void accept()}><Text message="Accept and continue"/></button><Link href="/" className="button secondary"><Text message="Back to marketplace"/></Link><Link href="/delete-account"><Text message="Delete account and data"/></Link>{error?<p role="alert">{error}</p>:null}</div></dialog>:null}</>;
}
