"use client";


import {Text,Localized} from '@/components/localization';
import React from 'react';
import {ArrowDown,ArrowUp,CalendarClock,Clock3,Plus,RefreshCw,Trash2,Truck,UserRound} from 'lucide-react';
import {buildFeaturedDaySchedule,DEFAULT_FEATURED_SCHEDULE_CONFIG} from '@/lib/expo-broadcast.js';
import {vehicleConfigurationImage} from '@/lib/vehicle-configurations';

type Candidate={truck_key:string;vehicle_id:string;driver_user_id:string;platform_number?:string;cargo_configuration:string;driver_first_name:string;driver_kind_label:string;name:string;base_place:string};
type ManualInterval={providerKey:string;startTime:string;endTime:string};
type Sponsor={sponsor_name?:string;eligible?:boolean;starts_on?:string;ends_on?:string};

function ethiopiaTime(iso:string){return new Intl.DateTimeFormat('en-GB',{timeZone:'Africa/Addis_Ababa',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(iso));}

export function FeaturedRosterEditor({candidates,selectedProviderKeys,featureDate,defaultSchedule,defaultManualSchedule=[],sponsors=[]}:{candidates:Candidate[];selectedProviderKeys:string[];featureDate:string;defaultSchedule?:any;defaultManualSchedule?:ManualInterval[];sponsors?:Sponsor[]} ){
  const [selected,setSelected]=React.useState(selectedProviderKeys as string[]);
  const [candidateKey,setCandidateKey]=React.useState('');
  const [ready,setReady]=React.useState(false);
  const [mode,setMode]=React.useState((defaultSchedule?.mode==='MANUAL'?'MANUAL':'AUTO') as 'AUTO'|'MANUAL');
  const [config,setConfig]=React.useState({...DEFAULT_FEATURED_SCHEDULE_CONFIG,...(defaultSchedule?.config||{}),dayStart:'08:30',dayEnd:'12:00',targetCount:Math.min(8,defaultSchedule?.config?.targetCount||8)} as any);
  const [legacyNeedsReview,setLegacyNeedsReview]=React.useState(defaultSchedule?.config?.dayStart==='07:30');
  const [manual,setManual]=React.useState(defaultManualSchedule as ManualInterval[]);
  React.useEffect(()=>setReady(true),[]);
  const byKey=React.useMemo(()=>new Map(candidates.map(candidate=>[candidate.truck_key,candidate])),[candidates]);
  const selectedDrivers=new Set(selected.map((key:string)=>byKey.get(key)?.driver_user_id).filter(Boolean));
  const available=candidates.filter(candidate=>!selected.includes(candidate.truck_key)&&!selectedDrivers.has(candidate.driver_user_id));
  let schedule:any=null;let scheduleError='';
  try{
    schedule=buildFeaturedDaySchedule(featureDate,selected,{mode,config,manualSchedule:manual});
    const names=sponsors.filter((item:Sponsor)=>item.eligible!==false&&(!item.starts_on||item.starts_on<=featureDate)&&(!item.ends_on||item.ends_on>=featureDate)).map((item:Sponsor)=>item.sponsor_name).filter(Boolean) as string[];
    let index=0;schedule={...schedule,entries:schedule.entries.map((entry:any)=>entry.type==='PROGRAMME_BREAK'&&names.length?{...entry,label:'Sponsor · '+names[index++%names.length]}:entry)};
  }catch(error){scheduleError=error instanceof Error&&error.message.includes('MANUAL')?'Keep truck times in order from 08:30 to 12:00, with no more than four gaps of up to two minutes.':'Check the programme settings.';}
  const walkthroughByKey=new Map((schedule?.walkthroughs||[]).map((item:any)=>[item.provider_key,item]));
  function move(index:number,direction:-1|1){
    const next=[...selected],target=index+direction;if(target<0||target>=next.length)return;
    [next[index],next[target]]=[next[target],next[index]];
    if(mode==='MANUAL')setManual(next.map((key,position)=>{const slot=manual.find((item:ManualInterval)=>item.providerKey===selected[position]);return {providerKey:key,startTime:slot?.startTime||'',endTime:slot?.endTime||''};}));
    setSelected(next);
  }
  function updateManual(key:string,field:'startTime'|'endTime',value:string){setManual((current:ManualInterval[])=>{const existing=current.find((item:ManualInterval)=>item.providerKey===key)||{providerKey:key,startTime:'',endTime:''};return [...current.filter((item:ManualInterval)=>item.providerKey!==key),{...existing,[field]:value}];});}
  function switchMode(next:'AUTO'|'MANUAL'){if(next==='AUTO')setLegacyNeedsReview(false);if(next==='MANUAL'&&mode!=='MANUAL'){const automatic=buildFeaturedDaySchedule(featureDate,selected,{config});setManual(automatic.walkthroughs.map((item:any)=>({providerKey:item.provider_key,startTime:ethiopiaTime(item.starts_at),endTime:ethiopiaTime(item.ends_at)})));}setMode(next);}
  return <section className="panel featured-roster-editor"><div className="section-heading"><div><span className="section-kicker"><Truck aria-hidden="true"/><Text message="Featured trucks"/></span><h2><Text message="Choose today's trucks and Drivers"/></h2></div><strong className="featured-roster-count">{selected.length}/{config.targetCount}</strong></div>
    {legacyNeedsReview&&mode==='MANUAL'?<p className="notice"><Text message="This day uses the previous hours. Choose Automatic to start a new timetable, then Manual to adjust it."/></p>:null}
    {selected.map((key:string)=><input key={key} type="hidden" name="truckKeys" value={key}/>)}
    <input type="hidden" name="sponsorBreakCount" value={config.sponsorBreakCount}/><input type="hidden" name="sponsorBreakMinutes" value={config.sponsorBreakMinutes}/><input type="hidden" name="scheduleMode" value={mode}/><input type="hidden" name="scheduleDayStart" value="08:30"/><input type="hidden" name="scheduleDayEnd" value="12:00"/><input type="hidden" name="manualSchedule" value={JSON.stringify(manual.filter((item:ManualInterval)=>selected.includes(item.providerKey)))}/>
    <div className="featured-roster-add"><div className="form-group"><label htmlFor="featured-truck-add"><Text message="Add truck and Driver"/></label><select id="featured-truck-add" value={candidateKey} disabled={!ready} onChange={event=>setCandidateKey(event.target.value)}><option value=""><Text message="Choose a truck"/></option>{available.map((candidate:Candidate)=><option key={candidate.truck_key} value={candidate.truck_key}>{candidate.cargo_configuration} · {candidate.driver_first_name} · {candidate.name}</option>)}</select></div><button className="button secondary" type="button" disabled={!ready||!candidateKey||selected.length>=8} onClick={()=>{if(candidateKey&&selected.length<8&&!selected.includes(candidateKey))setSelected((current:string[])=>[...current,candidateKey]);setCandidateKey('');}}><Plus aria-hidden="true"/><Text message="Add"/></button></div>
    {selected.length?<ol className="featured-roster-list">{selected.map((key:string,index:number)=>{const candidate=byKey.get(key);if(!candidate)return null;const walkthrough:any=walkthroughByKey.get(key);const interval=manual.find((item:ManualInterval)=>item.providerKey===key);return <li key={key}><span className="featured-roster-position">{String(index+1).padStart(2,'0')}</span><span className="featured-roster-provider"><Localized as="img" copy={["alt"]} src={vehicleConfigurationImage(candidate.cargo_configuration)} alt=""/><span><strong>{candidate.cargo_configuration}</strong><small><UserRound aria-hidden="true"/>{candidate.driver_first_name} · {candidate.driver_kind_label} · {candidate.name}</small></span></span>{mode==='MANUAL'?<span className="featured-manual-time"><label><small><Text message="Starts"/></small><input type="time" min="08:30" max="12:00" value={interval?.startTime||''} onChange={event=>updateManual(key,'startTime',event.target.value)}/></label><label><small><Text message="Ends"/></small><input type="time" min="08:30" max="12:00" value={interval?.endTime||''} onChange={event=>updateManual(key,'endTime',event.target.value)}/></label></span>:<span className="featured-roster-time"><Clock3 aria-hidden="true"/><strong>{walkthrough?.time_label||'Pending'}</strong></span>}<span className="featured-roster-actions"><button type="button" onClick={()=>move(index,-1)} disabled={index===0} aria-label={'Move '+candidate.cargo_configuration+' earlier'}><ArrowUp aria-hidden="true"/></button><button type="button" onClick={()=>move(index,1)} disabled={index===selected.length-1} aria-label={'Move '+candidate.cargo_configuration+' later'}><ArrowDown aria-hidden="true"/></button><button type="button" className="danger" onClick={()=>setSelected((current:string[])=>current.filter((item:string)=>item!==key))} aria-label={'Remove '+candidate.cargo_configuration}><Trash2 aria-hidden="true"/></button></span></li>;})}</ol>:<p className="empty-state compact"><Text message="Choose "/>{config.targetCount}<Text message=" trucks to publish this programme."/></p>}
    <div className="featured-broadcast-editor"><div className="featured-schedule-heading"><div><span className="section-kicker"><CalendarClock aria-hidden="true"/><Text message="08:30–12:00 EAT"/></span><h3><Text message="Morning programme"/></h3></div><Localized as="div" copy={["aria-label"]} className="featured-schedule-mode" role="group" aria-label="Schedule mode"><button type="button" className={mode==='AUTO'?'active':''} onClick={()=>switchMode('AUTO')}><RefreshCw aria-hidden="true"/><Text message="Automatic"/></button><button type="button" className={mode==='MANUAL'?'active':''} disabled={selected.length>8} onClick={()=>switchMode('MANUAL')}><Clock3 aria-hidden="true"/><Text message="Manual"/></button></Localized></div>
      <p className="meta"><Text message="Up to eight showcases, with four two-minute sponsor mentions by default. Staff run the TikTok broadcast separately."/></p>
      <div className="featured-schedule-settings"><label><span><Text message="Featured trucks"/></span><select name="targetCount" value={config.targetCount} onChange={event=>setConfig((current:any)=>({...current,targetCount:Number(event.target.value)}))}>{Array.from({length:8},(_,index)=>index+1).map(value=><option key={value}>{value}</option>)}</select></label><label><span><Text message="Sponsor mentions"/></span><select disabled={mode==='MANUAL'} value={config.sponsorBreakCount} onChange={event=>setConfig((current:any)=>({...current,sponsorBreakCount:Number(event.target.value)}))}>{[0,1,2,3,4].map(value=><option key={value} value={value}>{value}</option>)}</select></label><label><span><Text message="Mention length"/></span><select disabled={mode==='MANUAL'} value={config.sponsorBreakMinutes} onChange={event=>setConfig((current:any)=>({...current,sponsorBreakMinutes:Number(event.target.value)}))}>{[1,2].map(value=><option key={value} value={value}>{value}<Text message=" minute"/>{value===1?'':'s'}</option>)}</select></label></div>
      {mode==='MANUAL'?<p className="meta"><Text message="In Manual, gaps between truck times set the sponsor mentions. Moving a truck keeps the slot times in place."/></p>:null}
      {scheduleError?<p className="field-error" role="alert"><Text message={scheduleError}/></p>:schedule?<div className="featured-schedule-preview"><Localized as="ol" copy={["aria-label"]} className="featured-schedule-timeline" tabIndex={0} aria-label="Morning featured-truck schedule">{schedule.entries.map((entry:any,index:number)=><li key={entry.type+'-'+entry.starts_at+'-'+index} className={entry.type.toLowerCase().replace('_','-')}><span>{entry.time_label}</span><strong>{entry.type==='PROVIDER'?byKey.get(entry.provider_key)?.cargo_configuration:entry.label}</strong></li>)}</Localized></div>:null}
    </div>
  </section>;
}
