import {CircleCheck,Headphones,Paperclip,Send,UserRound} from 'lucide-react';
import {SupportRefresh} from './support-refresh';
import {StatusPill} from './status-pill';

export function GuestSupportThread({conversation,team=false}:{conversation:any;team?:boolean}){
  const open=conversation.status!=='CLOSED';
  return <section className="support-thread guest-support-thread" aria-label="Assisted matching conversation"><SupportRefresh enabled={open} intervalMs={2000}/>
    <header className="support-thread-header"><div><span className="section-kicker"><Headphones aria-hidden="true"/>Assisted matching</span><h1>{team?conversation.email:'Your conversation'}</h1><p className={`assisted-chat-agent ${conversation.assigned_agent_name?'online':'waiting'}`}><span aria-hidden="true"/>{conversation.assigned_agent_name?`Live · ${conversation.assigned_agent_name} is helping`:'Waiting for the next available team member'}</p></div><StatusPill status={conversation.status}/></header>
    <div className="support-messages" aria-live="polite">{conversation.messages.map((message:any)=>{const mine=team?message.sender_kind==='TEAM':message.sender_kind==='GUEST';return <article className={`support-message ${mine?'mine':''}`} key={message.id}><div className="support-message-sender">{message.sender_kind==='GUEST'?<UserRound aria-hidden="true"/>:<Headphones aria-hidden="true"/>}<strong>{mine?'You':message.sender_kind==='GUEST'?'Guest':'Loadgistic team'}</strong></div><p>{message.body}</p>{message.attachment_id?<a className="support-attachment" href={`/api/guest-support/${conversation.id}/attachments/${message.attachment_id}`}><Paperclip aria-hidden="true"/>{message.attachment_name}</a>:null}<time dateTime={message.created_at}>{new Date(message.created_at).toLocaleString()}</time></article>})}</div>
    {open?<><form className="support-composer" action={`/api/guest-support/${conversation.id}/messages`} method="post" encType="multipart/form-data"><label htmlFor="guest-support-reply"><Send aria-hidden="true"/>Message</label><textarea id="guest-support-reply" name="body" maxLength={2000} rows={3} required placeholder="Write a clear message"/><label className="support-file-field"><Paperclip aria-hidden="true"/><span>Requested file <small>(optional JPG, PNG, WebP, or PDF)</small></span><input type="file" name="file" accept="image/jpeg,image/png,image/webp,application/pdf"/></label><button className="button"><Send aria-hidden="true"/>Send</button></form>{team?<form className="support-close-action" action={`/api/guest-support/${conversation.id}/close`} method="post"><button className="button secondary small"><CircleCheck aria-hidden="true"/>Close conversation</button></form>:null}</>:<div className="support-closed-note"><CircleCheck aria-hidden="true"/><span><strong>Conversation closed</strong><small>This private transcript remains available during its retention period.</small></span></div>}
  </section>;
}
