import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import { listCapacity, listOwnVehicles } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { Flash } from '@/components/flash';
import { StatusPill } from '@/components/status-pill';
import { capacityLabel } from '@/lib/domain.js';

export default async function CapacityPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); const query=await searchParams; const rows:any[]=listCapacity(user); const vehicles:any[]=listOwnVehicles(user); const canPublish=['TRANSPORTER','DRIVER'].includes(user.role);
 return <div className="page"><PageHeader title="Truck capacity" subtitle="Simple availability: Empty, Partial, or Full. Freshness comes from the verified account update time."/><Flash error={query.error} success={query.success}/>
 {canPublish?<section className="capacity-hero" style={{marginBottom:20}}><div><span className="status green">Supply visibility</span><h2 style={{marginTop:12}}>Keep capacity fresh and honest</h2><p className="muted">Partial capacity uses one estimated available percentage. A photo is optional.</p></div><a href="#update" className="button">Update capacity</a></section>:<div className="alert">Only fresh, visibility-permitted capacity is shown. Expired updates disappear from discovery.</div>}
 <div className={canPublish?'two-col':'stack'}><section><div className="stack">{rows.map((cap:any)=><article className="card" key={cap.id}><div style={{display:'flex',justifyContent:'space-between',gap:12,flexWrap:'wrap'}}><div><div style={{display:'flex',gap:8,flexWrap:'wrap'}}><StatusPill status={cap.status}/><StatusPill status={cap.freshness}/>{cap.isOwn?<span className="status">Your capacity</span>:null}</div><h3 style={{fontSize:'1.2rem',marginTop:12}}>{cap.organization_name||cap.provider_name}</h3><div className="meta">{cap.vehicle_label} · {cap.vehicle_category}</div></div><div style={{textAlign:'right'}}><strong style={{fontSize:'1.3rem'}}>{capacityLabel(cap.status,cap.available_percent)}</strong><div className="meta">{cap.corridor||`${cap.origin||'Origin'} → ${cap.destination||'Destination'}`}</div></div></div><div className="progress" style={{margin:'16px 0 10px'}}><span style={{width:`${cap.available_percent}%`}}/></div><div className="split"><div className="meta"><strong>Updated in Loadgistic by {cap.updated_by_name}</strong><br/>{new Date(cap.updated_at).toLocaleString()}</div><div className="meta"><strong>Expires</strong><br/>{new Date(cap.expires_at).toLocaleString()}</div></div>{cap.photo_path?<div className="alert success" style={{marginTop:12,marginBottom:0}}>Capacity photo attached</div>:null}{cap.organization_handle||cap.provider_handle?<div style={{marginTop:12}}><Link className="button secondary small" href={`/companies/${cap.organization_handle||cap.provider_handle}`}>View provider page</Link></div>:null}</article>)}</div>{!rows.length?<div className="empty">No current capacity is visible.</div>:null}</section>
 {canPublish?<aside id="update" className="form-card"><h2 style={{fontSize:'1.35rem'}}>Update capacity</h2><form action="/api/capacity" method="post" encType="multipart/form-data" className="stack" data-testid="capacity-form"><div className="form-group"><label>Vehicle</label><select name="vehicleId" required>{vehicles.map((v:any)=><option value={v.id} key={v.id}>{v.label} — {v.category}</option>)}</select></div><div className="form-group"><label>Status</label><select name="status" defaultValue="EMPTY"><option value="EMPTY">Empty — 100% available</option><option value="PARTIAL">Partial</option><option value="FULL">Full — 0% available</option></select></div><div className="form-group"><label>Available percentage (Partial only)</label><input name="availablePercent" type="number" min="1" max="99" placeholder="40"/></div><div className="form-group"><label>Origin</label><input name="origin" placeholder="Addis Ababa"/></div><div className="form-group"><label>Destination</label><input name="destination" placeholder="Dire Dawa"/></div><div className="form-group"><label>Corridor</label><input name="corridor" placeholder="Addis Ababa → Dire Dawa"/></div><div className="form-group"><label>Travel date</label><input name="travelDate" type="date"/></div><div className="form-group"><label>Next available (optional)</label><input name="nextAvailable" placeholder="Tomorrow 08:00"/></div><div className="form-group"><label>Visibility</label><select name="visibility" defaultValue="OPEN"><option value="OPEN">Open to verified businesses</option><option value="SAVED_PARTNERS">Saved partners</option><option value="PRIVATE">Private</option></select></div><div className="form-group"><label>Capacity photo (optional)</label><input name="photo" type="file" accept="image/jpeg,image/png,image/webp"/></div><button className="button">Publish update</button></form></aside>:null}</div></div>;
}
