import Link from 'next/link';
import Image from 'next/image';
import { requireUser } from '@/lib/auth';
import { listMarketCapacityPage, listOwnLoadRouteOptions } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { StatusPill } from '@/components/status-pill';
import { capacityLabel } from '@/lib/domain.js';
import { relativeTime } from '@/lib/ui';
import { vehicleConfigurationImage } from '@/lib/vehicle-configurations';
import { VEHICLE_CONFIGURATIONS } from '@/lib/vehicle-configurations';
import { CalendarClock, Camera, CircleDotDashed, Eye, Gauge, Route, Search, SlidersHorizontal, X } from 'lucide-react';
import { Pagination } from '@/components/pagination';
import { BoardGeographyFilters } from '@/components/board-geography-filters';
import { EthiopiaPlaceInput } from '@/components/ethiopia-place-input';

function acceptedLoads(capacity:any) {
  if (capacity.accepts_full_load && capacity.accepts_partial_load) return 'FTL + PTL';
  if (capacity.accepts_partial_load) return 'PTL';
  return 'FTL';
}

function stopPolicy(capacity:any){
  const options=['Direct'];
  if(capacity.accepts_multi_pick)options.push('Multi Pick');
  if(capacity.accepts_multi_drop)options.push('Multi Drop');
  return options.join(' + ');
}

export default async function CapacityPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); const query=await searchParams; const filters={q:query.q||'',movementScope:query.movementScope||'',localPlaceRef:query.localPlaceRef||'',locality:query.locality||'',localRadiusKm:query.localRadiusKm||'50',originPlaceRef:query.originPlaceRef||'',origin:query.origin||'',originRadiusKm:query.originRadiusKm||'50',destinationPlaceRef:query.destinationPlaceRef||'',destination:query.destination||'',destinationRadiusKm:query.destinationRadiusKm||'50',directionMode:query.directionMode||'DIRECT',currentAreaPlaceRef:query.currentAreaPlaceRef||'',currentArea:query.currentArea||'',currentAreaRadiusKm:query.currentAreaRadiusKm||'50',currentAreaMode:query.currentAreaMode||'PREFER',status:query.status||'',loadType:query.loadType||'',vehicleCategory:query.vehicleCategory||'',matchLoadId:query.matchLoadId||'',minAvailable:query.minAvailable||'',routeBy:query.routeBy||'',visibility:query.visibility||'',freshness:query.freshness||'',stopOption:query.stopOption||'',contractRoutes:query.contractRoutes||'',proof:query.proof||''}; const result:any=listMarketCapacityPage(user,filters,{page:query.page,pageSize:12}); const rows:any[]=result.items; const isProvider=['TRANSPORTER','DRIVER'].includes(user.role); const loadRoutes:any[]=listOwnLoadRouteOptions(user); const hasFilters=[filters.q,filters.movementScope,filters.localPlaceRef,filters.originPlaceRef,filters.destinationPlaceRef,filters.currentAreaPlaceRef,filters.status,filters.loadType,filters.vehicleCategory,filters.matchLoadId,filters.minAvailable,filters.routeBy,filters.visibility,filters.freshness,filters.stopOption,filters.contractRoutes,filters.proof].some(Boolean); const hasAdvancedFilters=[filters.minAvailable,filters.routeBy,filters.visibility,filters.freshness,filters.stopOption,filters.contractRoutes,filters.proof,filters.currentAreaPlaceRef].some(Boolean);
 return <div className="page"><PageHeader title="Capacity Board" subtitle={isProvider?'A read-only view of current supply signals from other trucks.':'Every card is one fresh Empty or Partial truck available for freight work.'}/>
 {isProvider?<div className="alert">The Capacity Board is read only for transporters and drivers. Use it to understand supply; contact and interest actions are not available here.</div>:<div className="alert">Each truck stands on its own. Public means all logged-in businesses; Partners means only Connected network Businesses.</div>}
 <form className="board-filter-panel" method="get">
   <div className="board-filter-heading"><SlidersHorizontal aria-hidden="true"/><div><h2>Find the closest capacity</h2><p>Search directly or rank trucks against one of your load routes.</p></div></div>
   <div className="board-filter-grid">
     <div className="form-group filter-search"><label htmlFor="capacity-search"><Search aria-hidden="true"/>Search</label><input id="capacity-search" name="q" defaultValue={filters.q} placeholder="Truck, transporter, or cargo configuration"/></div>
     {loadRoutes.length?<div className="form-group filter-match"><label htmlFor="capacity-match"><Route aria-hidden="true"/>Match a posted load</label><select id="capacity-match" name="matchLoadId" defaultValue={filters.matchLoadId}><option value="">Do not rank by a load</option>{loadRoutes.map(load=><option key={load.id} value={load.id}>{load.code} · {load.movement_scope==='LOCAL'?`Local in ${load.local_place_label}`:`${load.origin} → ${load.destination}`}</option>)}</select></div>:null}
     <BoardGeographyFilters idPrefix="capacity" movementScope={filters.movementScope} localPlaceRef={filters.localPlaceRef} locality={filters.locality} localRadiusKm={filters.localRadiusKm} originPlaceRef={filters.originPlaceRef} origin={filters.origin} originRadiusKm={filters.originRadiusKm} destinationPlaceRef={filters.destinationPlaceRef} destination={filters.destination} destinationRadiusKm={filters.destinationRadiusKm} directionMode={filters.directionMode} routeLabels={['Route city 1','Route city 2']}/>
     <div className="form-group"><label htmlFor="capacity-status">Cargo space</label><select id="capacity-status" name="status" defaultValue={filters.status}><option value="">Empty or Partial</option><option value="EMPTY">Empty</option><option value="PARTIAL">Partial</option></select></div>
     <div className="form-group"><label htmlFor="capacity-load-type">Accepts</label><select id="capacity-load-type" name="loadType" defaultValue={filters.loadType}><option value="">FTL or PTL</option><option value="FTL">FTL</option><option value="PTL">PTL</option></select></div>
     <div className="form-group"><label htmlFor="capacity-truck-type">Cargo configuration</label><select id="capacity-truck-type" name="vehicleCategory" defaultValue={filters.vehicleCategory}><option value="">All truck types</option>{VEHICLE_CONFIGURATIONS.map(type=><option value={type.name} key={type.name}>{type.name}</option>)}</select></div>
   </div>
   <details className="board-more-filters" open={hasAdvancedFilters}>
     <summary><SlidersHorizontal aria-hidden="true"/>More filters</summary>
     <div className="board-filter-grid">
       <div className="form-group"><label htmlFor="capacity-min-space"><Gauge aria-hidden="true"/>At least this much space</label><select id="capacity-min-space" name="minAvailable" defaultValue={filters.minAvailable}><option value="">Any available space</option><option value="25">25% or more</option><option value="50">50% or more</option><option value="75">75% or more</option><option value="100">100% empty</option></select></div>
       <div className="form-group"><label htmlFor="capacity-route-by"><CalendarClock aria-hidden="true"/>Route date before or on</label><input id="capacity-route-by" name="routeBy" type="date" defaultValue={filters.routeBy}/></div>
       <div className="form-group"><label htmlFor="capacity-visibility"><Eye aria-hidden="true"/>Visibility</label><select id="capacity-visibility" name="visibility" defaultValue={filters.visibility}><option value="">Public or Partners</option><option value="OPEN">Public</option><option value="SAVED_PARTNERS">Partners</option></select></div>
       <div className="form-group"><label htmlFor="capacity-freshness"><Gauge aria-hidden="true"/>Freshness</label><select id="capacity-freshness" name="freshness" defaultValue={filters.freshness}><option value="">Any fresh Board signal</option><option value="FRESH">Current</option><option value="UPDATE_NEEDED">Update needed</option></select></div>
       <div className="form-group"><label htmlFor="capacity-stops"><Route aria-hidden="true"/>Route flexibility</label><select id="capacity-stops" name="stopOption" defaultValue={filters.stopOption}><option value="">Any route flexibility</option><option value="DIRECT_ONLY">Direct only</option><option value="MULTI_PICK">Accepts Multi Pick</option><option value="MULTI_DROP">Accepts Multi Drop</option></select></div>
       <div className="form-group"><label htmlFor="capacity-contract-routes"><Route aria-hidden="true"/>Contract routes</label><select id="capacity-contract-routes" name="contractRoutes" defaultValue={filters.contractRoutes}><option value="">Any contract preference</option><option value="YES">Open to contract routes</option></select></div>
       <div className="form-group"><label htmlFor="capacity-proof"><Camera aria-hidden="true"/>Cargo-space proof</label><select id="capacity-proof" name="proof" defaultValue={filters.proof}><option value="">With or without proof</option><option value="RECORDED">Photo recorded</option></select></div>
       <div className="form-group"><label htmlFor="capacity-current-area"><CircleDotDashed aria-hidden="true"/>Current truck area near</label><EthiopiaPlaceInput id="capacity-current-area" name="currentArea" placeRefName="currentAreaPlaceRef" defaultPlaceRef={filters.currentAreaPlaceRef} defaultValue={filters.currentArea} placeholder="Adama, Ethiopia"/></div>
       <div className="form-group"><label htmlFor="capacity-current-area-radius">Search radius</label><select id="capacity-current-area-radius" name="currentAreaRadiusKm" defaultValue={filters.currentAreaRadiusKm}><option value="10">10 km</option><option value="25">25 km</option><option value="50">50 km</option><option value="100">100 km</option><option value="200">200 km</option></select></div>
       <div className="form-group"><label htmlFor="capacity-current-area-mode">Current area match</label><select id="capacity-current-area-mode" name="currentAreaMode" defaultValue={filters.currentAreaMode}><option value="PREFER">Show nearby first</option><option value="REQUIRE">Only nearby trucks</option></select></div>
     </div>
   </details>
   <div className="board-filter-actions"><button className="button icon-button-label"><Search aria-hidden="true"/>Show matching trucks</button>{hasFilters?<Link href="/app/capacity" className="button secondary icon-button-label"><X aria-hidden="true"/>Clear</Link>:null}<span className="meta">{result.total} {result.total===1?'truck':'trucks'} found</span></div>
 </form>
 <section className="capacity-market-grid">{rows.map((cap:any)=><article className="card capacity-market-card" key={cap.id}>
   <div className="market-card-top"><div className="market-truck-heading"><Image className="truck-thumbnail large" src={vehicleConfigurationImage(cap.cargo_configuration||cap.vehicle_category)} alt="" width={120} height={120}/><div><div className="status-row"><StatusPill status={cap.status}/><StatusPill status={cap.freshness}/>{cap.relationshipVisible?<span className="status green">Partners</span>:<span className="status">Public</span>}</div><h2>{cap.vehicle_make} · {cap.vehicle_model}</h2><div className="meta">{cap.platform_number} · {cap.cargo_configuration||cap.vehicle_category}<br/>{cap.organization_name||cap.provider_name}</div></div></div><strong className="market-capacity-value">{capacityLabel(cap.status,cap.available_percent)}</strong></div>
   <div className="progress"><span style={{width:`${cap.available_percent}%`}}/></div>
   <div className="market-signal-grid"><div><small>Current area</small><strong>{cap.movement_scope!=='INTERCITY'&&cap.local_place_label?`${cap.local_place_label} · ${cap.local_radius_km} km radius`:cap.location_area||cap.origin||'Area not updated'}</strong><span>{cap.movement_scope==='LOCAL'?'Declared Local service area':cap.location_source === 'DEVICE_OBSCURED' ? `Approximate device area · ${cap.location_precision_km} km privacy zone` : cap.location_updated_at?`Updated ${relativeTime(cap.location_updated_at)}`:'Location time unavailable'}</span></div><div><small>{cap.movement_scope==='LOCAL'?'Movement':cap.status==='PARTIAL'?'Current partial route':'Planned route'}</small>{cap.movement_scope==='LOCAL'?<><strong>Local availability</strong><span>No between-city route required</span></>:<><strong>{cap.status==='PARTIAL'?(cap.current_route_origin||'Not recorded'):(cap.origin||'Not recorded')} → {cap.status==='PARTIAL'?(cap.current_route_destination||'Not recorded'):(cap.destination||'Not recorded')}</strong><span>{cap.status==='PARTIAL'?(cap.current_route_date||'No current-route date'):(cap.travel_date?`${cap.travel_date} · ${cap.planned_space_status==='PARTIAL'?'Partial':'Full'} cargo space`:'No planned date')}</span></>}</div><div><small>Accepting</small><strong>{acceptedLoads(cap)}</strong><span>{stopPolicy(cap)} · {cap.open_to_contract_lanes?'Contract routes':'Single-trip work'}</span></div><div><small>Proof signal</small><strong>{cap.proof_available?'Photo recorded':'No photo'}</strong><span>{cap.proof_recorded_at?relativeTime(cap.proof_recorded_at):'Not recorded'}</span></div></div>
   <div className="market-card-actions">{cap.route_match_label?<span className={`route-match match-${cap.route_match_score}`}><Route aria-hidden="true"/>{cap.route_match_label}{cap.route_match_source?` · ${cap.route_match_source}`:''}</span>:null}<Link className="button secondary small" href={`/app/capacity/${cap.id}`}>View truck details</Link></div>
 </article>)}</section>{!rows.length?<div className="empty-state">No fresh capacity is visible right now.</div>:null}<Pagination path="/app/capacity" query={filters} page={result.page} pageCount={result.pageCount} total={result.total}/></div>;
}
