import { notFound } from 'next/navigation';
import Image from 'next/image';
import Link from 'next/link';
import { getNetworkState, getProfileRouteComparison, getPublicCompany, paginateResults } from '@/lib/repository.js';
import { StatusPill } from '@/components/status-pill';
import { capacityLabel } from '@/lib/domain.js';
import { requireUser } from '@/lib/auth';
import { vehicleConfigurationImage } from '@/lib/vehicle-configurations';
import { VerificationBadges } from '@/components/verification-badges';
import { RouteCoverageMap } from '@/components/route-coverage-map';
import { Building2, CirclePlus, Eye, Gauge, GitCompareArrows, Mail, MapPin, Phone, Route, Send, Star, Truck, X } from 'lucide-react';
import { NetworkActions } from '@/components/network-actions';
import { Flash } from '@/components/flash';
import { Pagination } from '@/components/pagination';

export default async function CompanyPage({ params,searchParams }: { params: Promise<{ handle: string }>; searchParams:Promise<Record<string,string|undefined>> }) {
  const { handle } = await params;
  const query=await searchParams;
  const user=await requireUser();
  const company:any = getPublicCompany(handle);
  if (!company) notFound();
  const comparison=query.compare==='coverage'?getProfileRouteComparison(user,company):null;
  const isBusiness=Boolean(company.is_business);
  const canSendProviderRequest=!isBusiness&&['SHIPPER','RECEIVER'].includes(user.role);
  const canSelectReceiver=isBusiness&&['SHIPPER','RECEIVER'].includes(user.role)&&company.id!==user.organization_id;
  const isOwnProfile=(company.page_kind==='organization'&&company.id===user.organization_id)||(company.page_kind==='provider'&&company.id===user.provider_profile_id);
  const providerRef = `${company.page_kind === 'provider' ? 'profile' : 'org'}:${company.id}`;
  const initials = String(company.name || company.business_name).split(' ').slice(0,2).map((v:string)=>v[0]).join('');
  const hasContact=Boolean(company.contact_phone||company.contact_email);
  const routeResult:any=paginateResults(company.routes||[],{page:query.routePage,pageSize:10});
  const areaResult:any=paginateResults(company.service_areas||[],{page:query.areaPage,pageSize:10});
  const liveRouteResult:any=paginateResults(company.live_routes||[],{page:query.liveRoutePage,pageSize:10});
  const vehicleResult:any=paginateResults(company.vehicles||[],{page:query.truckPage,pageSize:12});
  const capacityResult:any=paginateResults(company.capacities||[],{page:query.capacityPage,pageSize:10});

  const networkState=getNetworkState(user,company.page_kind==='provider'?'profile':'org',company.id);
  return <div className="page"><Flash error={query.error} success={query.success}/>
    <div className="company-hero"><div className="company-logo">{initials}</div><div><div className="profile-title-line"><h1 className="page-title">{company.name}</h1>{company.verified?<StatusPill status="Approved"/>:null}</div><p className="page-subtitle">{company.headline}</p><div className="meta icon-meta"><MapPin aria-hidden="true"/>{company.city||'Location not added'} · {isBusiness?'Business':String(company.type).replaceAll('_',' ')}</div><VerificationBadges badges={company.verification_badges}/></div><div className="hero-actions">{canSendProviderRequest?<Link className="button" href={`/app/shipments/new?provider=${providerRef}`}><Send aria-hidden="true"/>Request</Link>:null}{canSelectReceiver?<Link className="button" href={`/app/shipments/new?receiver=${company.id}`}><CirclePlus aria-hidden="true"/>Create shipment</Link>:null}{!isOwnProfile&&(company.map_routes.length||company.map_areas.length)?<Link className="button secondary icon-button-label" href={`/app/providers/${handle}?compare=coverage#route-coverage`}><GitCompareArrows aria-hidden="true"/>Compare routes</Link>:null}<NetworkActions state={networkState} targetKind={company.page_kind==='provider'?'profile':'org'} targetId={company.id} returnTo={`/app/providers/${handle}`}/></div></div>

    <div className="two-col" style={{marginTop:20}}><div className="stack">
	      <section className="card profile-overview"><h2 className="panel-heading"><Building2 aria-hidden="true"/>{isBusiness?'About this Business':'Overview'}</h2><p className="lede profile-about">{company.about || company.description || 'Profile information is being completed.'}</p>{company.services?<><h3>{isBusiness?'Products':'Services'}</h3><p>{company.services}</p></>:null}{company.operating_regions?<><h3><MapPin aria-hidden="true"/>{isBusiness?'Operating areas':'Service areas'}</h3><p>{company.operating_regions}</p></>:null}</section>

      <section className="card profile-route-coverage" id="route-coverage"><div className="page-header compact-header"><div><h2><Route aria-hidden="true"/>Coverage</h2><p className="page-subtitle">Local areas use circles. Routes use lines.</p></div>{comparison?<Link className="button secondary small" href={`/app/providers/${handle}#route-coverage`}><X aria-hidden="true"/>Hide compare</Link>:null}</div>
        {comparison?<div className="route-comparison-summary"><div><span>Coverage fit</span><strong>{comparison.strongest_label}</strong></div><div><span>Evidence</span><strong>{comparison.evidence_label}</strong></div><div><span>Shared view</span><strong>{comparison.exact_count} full routes · {comparison.area_overlap_count} local overlaps</strong></div></div>:null}
        {company.map_routes.length||company.map_areas.length?<RouteCoverageMap routes={company.map_routes} areas={company.map_areas} comparisonRoutes={comparison?.viewer_routes||[]} comparisonAreas={comparison?.viewer_areas||[]}/>:null}
        {areaResult.total?<><div className="profile-route-evidence service-area-evidence">{areaResult.items.map((area:any)=><article key={area.id}><div><strong>{area.place_label}<span>·</span>{area.radius_km} km radius</strong><small>{area.evidence_label}</small></div><dl><div><dt>{isBusiness?'Local shipments':'Capacity reports'}</dt><dd>{area.reported_count}</dd></div><div><dt>Tracked shipments</dt><dd>{area.tracked_count}</dd></div></dl></article>)}</div><Pagination path={`/app/providers/${handle}`} query={{compare:query.compare,routePage:query.routePage,liveRoutePage:query.liveRoutePage,truckPage:query.truckPage,capacityPage:query.capacityPage}} page={areaResult.page} pageCount={areaResult.pageCount} total={areaResult.total} pageParam="areaPage"/></>:null}
        {routeResult.total?<><div className="profile-route-evidence">{routeResult.items.map((route:any)=><article key={route.id}><div><strong>{route.origin}<span>↔</span>{route.destination}</strong><small>{route.evidence_label}</small></div><dl><div><dt>{isBusiness?'Shipments posted':'Capacity reports'}</dt><dd>{route.reported_count}</dd></div><div><dt>Tracked shipments</dt><dd>{route.tracked_count}</dd></div></dl></article>)}</div><Pagination path={`/app/providers/${handle}`} query={{compare:query.compare,liveRoutePage:query.liveRoutePage,truckPage:query.truckPage,capacityPage:query.capacityPage}} page={routeResult.page} pageCount={routeResult.pageCount} total={routeResult.total} pageParam="routePage"/></>:<div className="empty-state">No {isBusiness?'Freight':'Preferred'} Routes declared yet.</div>}
        {!isBusiness&&liveRouteResult.total?<div className="live-route-list"><h3>Fresh truck routes</h3>{liveRouteResult.items.map((route:any)=><article key={route.id}><div><span className={`status ${route.route_kind==='CURRENT_PARTIAL'?'green':''}`}>{route.source_label}</span><strong>{route.origin} → {route.destination}</strong><small>{route.platform_number} · {route.route_kind==='CURRENT_PARTIAL'?'Live now':route.route_date} · {route.planned_space_status==='FULL'?'Full':'Partial'} cargo space</small></div><span className="meta">Expires {new Date(route.expires_at).toLocaleString()}</span></article>)}<Pagination path={`/app/providers/${handle}`} query={{compare:query.compare,routePage:query.routePage,truckPage:query.truckPage,capacityPage:query.capacityPage}} page={liveRouteResult.page} pageCount={liveRouteResult.pageCount} total={liveRouteResult.total} pageParam="liveRoutePage"/></div>:null}
        {comparison?<div className="comparison-explanation"><strong>How this comparison works</strong><p>Full route matches share both city endpoints in either direction. Partial matches share one endpoint. Local circles match when their operating areas overlap, and routes can align when an endpoint falls inside a circle. Declarations without supporting records remain clearly labeled.</p>{comparison.matches.filter((match:any)=>match.score>0).length?<div className="comparison-match-list">{comparison.matches.filter((match:any)=>match.score>0).map((match:any,index:number)=><div key={`${match.target.id}-${index}`}><StatusPill status={match.score===2?'FULL_MATCH':'PARTIAL_MATCH'}/><span>{match.viewer.origin} ↔ {match.viewer.destination}</span><strong>{match.target.origin} ↔ {match.target.destination}</strong></div>)}</div>:comparison.area_overlap_count||comparison.route_area_count?<p className="meta">The visible fit comes from Local Service Areas or route endpoints inside those areas.</p>:<p className="meta">No recorded coverage overlap was found. This does not mean either member cannot serve the other.</p>}</div>:null}
      </section>

      {!isBusiness?<section className="card"><div className="page-header compact-header"><div><h2><Truck aria-hidden="true"/>Trucks</h2><p className="page-subtitle">{company.fleet_size} registered.</p></div></div><div className="provider-truck-roster">{vehicleResult.items.map((vehicle:any)=>{const publicCapacity=company.capacities.find((capacity:any)=>capacity.vehicle_id===vehicle.vehicle_id);const latestFresh=vehicle.capacity_id&&new Date(vehicle.expires_at).getTime()>Date.now();const displayStatus=vehicle.status==='OFF_DUTY'?'OFF_DUTY':latestFresh?vehicle.status:'NOT_UPDATED';return <article className="provider-truck-row" key={vehicle.vehicle_id}><Image src={vehicleConfigurationImage(vehicle.cargo_configuration||vehicle.category)} alt={vehicle.cargo_configuration||vehicle.category} width={100} height={100}/><div><strong>{vehicle.make} · {vehicle.model}</strong><div className="meta">{vehicle.platform_number} · {vehicle.cargo_configuration||vehicle.category}</div><VerificationBadges badges={vehicle.verification_badges} compact/></div><StatusPill status={displayStatus}/>{publicCapacity?<Link className="button secondary small" href={`/?truck=${encodeURIComponent(publicCapacity.id)}`}><Eye aria-hidden="true"/>View on public map</Link>:<span className="meta">{displayStatus==='OFF_DUTY'?'Hidden from Truck Market':'No current public capacity'}</span>}</article>})}</div><Pagination path={`/app/providers/${handle}`} query={{compare:query.compare,routePage:query.routePage,liveRoutePage:query.liveRoutePage,capacityPage:query.capacityPage}} page={vehicleResult.page} pageCount={vehicleResult.pageCount} total={vehicleResult.total} pageParam="truckPage"/></section>:null}
    </div>

    <aside className="stack">
      {isBusiness?<section className="card"><h3><Star aria-hidden="true"/>Business rating</h3><div className="rating-summary"><strong>{company.review_count?`${company.average_rating} / 5`:'New'}</strong><span>{company.review_count||0} completed-shipment reviews</span></div></section>:<section className="card"><h3><Truck aria-hidden="true"/>Fleet facts</h3><div className="detail-facts single"><div><span>Registered trucks</span><strong>{company.fleet_size}</strong></div><div><span>On Truck Board</span><strong>{company.capacities.length}</strong></div></div></section>}
      <section className="card"><h3><Building2 aria-hidden="true"/>Public contact</h3>{hasContact?<div className="public-contact-list">{company.contact_phone?<a href={`tel:${company.contact_phone}`}><Phone aria-hidden="true"/>{company.contact_phone}</a>:null}{company.contact_email?<a href={`mailto:${company.contact_email}`}><Mail aria-hidden="true"/>{company.contact_email}</a>:null}</div>:<p className="muted">No public contact added.</p>}<p className="meta">Account login contacts are private and never shown here.</p></section>
      {!isBusiness&&capacityResult.total?<section className="card"><h3><Gauge aria-hidden="true"/>Public capacity</h3><div className="stack">{capacityResult.items.map((cap:any)=><Link href={`/?truck=${encodeURIComponent(cap.id)}`} key={cap.id}><strong>{cap.vehicle_make} · {cap.vehicle_model}</strong><div className="meta">{cap.platform_number} · {capacityLabel(cap.status)}</div><div className="meta">{cap.status==='PARTIAL'&&cap.current_route_origin?`${cap.current_route_origin} → ${cap.current_route_destination}`:cap.origin&&cap.destination?`${cap.origin} → ${cap.destination}`:cap.movement_scope==='LOCAL'?`Local in ${cap.local_place_label} · ${cap.local_radius_km} km radius`:cap.movement_scope==='BOTH'&&cap.local_place_label?`Local in ${cap.local_place_label}`:'Willing to go anywhere'}</div></Link>)}</div><Pagination path={`/app/providers/${handle}`} query={{compare:query.compare,routePage:query.routePage,liveRoutePage:query.liveRoutePage,truckPage:query.truckPage}} page={capacityResult.page} pageCount={capacityResult.pageCount} total={capacityResult.total} pageParam="capacityPage"/></section>:null}
    </aside></div>
  </div>;
}
