import Link from 'next/link';
import Image from 'next/image';
import { redirect } from 'next/navigation';
import { requireUser } from '@/lib/auth';
import { getDashboard, listFleetDrivers, listOwnCapacity, listOwnVehicles, paginateResults } from '@/lib/repository.js';
import { PageHeader } from '@/components/page-header';
import { StatusPill } from '@/components/status-pill';
import { relativeTime } from '@/lib/ui';
import { vehicleConfigurationImage } from '@/lib/vehicle-configurations';
import { Flash } from '@/components/flash';
import { Pagination } from '@/components/pagination';
import { Eye, KeyRound, Save, ShieldCheck, Truck, UserRound } from 'lucide-react';

export default async function FleetPage({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
 const user=await requireUser(); if(user.role!=='TRANSPORTER') redirect('/app/home'); const query=await searchParams;
 const data:any=getDashboard(user); const allVehicles:any[]=listOwnVehicles(user); const vehicleResult:any=paginateResults(allVehicles,{page:query.truckPage,pageSize:10}); const vehicles:any[]=vehicleResult.items; const capacities:any[]=listOwnCapacity(user); const driverResult:any=paginateResults(listFleetDrivers(user),{page:query.driverPage,pageSize:10}); const drivers:any[]=driverResult.items; const latest=new Map(); for(const item of capacities)if(!latest.has(item.vehicle_id))latest.set(item.vehicle_id,item);
 return <div className="page"><PageHeader icon={Truck} title="My Fleet" subtitle="Trucks and driver access."/>
 <Flash error={query.error} success={query.success}/>
 <section className="stats">{Object.entries(data.counts).map(([label,value])=><div className="stat" key={label}><span className="meta">{label}</span><strong>{String(value)}</strong></div>)}</section>
 <section className="card"><div className="page-header compact-header"><div><h2><Truck aria-hidden="true"/>Trucks</h2><p className="page-subtitle">Capacity by truck.</p></div></div><div className="list">{vehicles.map(vehicle=>{const cap:any=latest.get(vehicle.id);return <div className="list-row fleet-truck-row" key={vehicle.id}><Image className="truck-thumbnail" src={vehicleConfigurationImage(vehicle.cargo_configuration||vehicle.category)} alt={vehicle.cargo_configuration||vehicle.category} width={96} height={96}/><div><strong>{vehicle.make} · {vehicle.model}</strong><div className="meta">{vehicle.platform_number} · {vehicle.cargo_configuration||vehicle.category}<br/>Plate: {vehicle.plate||'not recorded'}</div></div><div><strong>{cap?.location_area||'Location not updated'}</strong><div className="meta">{cap?.location_updated_at?relativeTime(cap.location_updated_at):'No location timestamp'}</div>{cap?<StatusPill status={cap.freshness}/>:null}</div><div>{cap?.status==='BUSY'&&cap?.expiry_state==='EXPIRED'?<span className="status expired">Ready date passed</span>:cap?<StatusPill status={cap.status}/>:<span className="status expired">Not published</span>}</div><Link href={`/app/fleet/${vehicle.id}`} className="button secondary small"><Eye aria-hidden="true"/>Truck</Link></div>})}</div><Pagination path="/app/fleet" query={{driverPage:query.driverPage}} page={vehicleResult.page} pageCount={vehicleResult.pageCount} total={vehicleResult.total} pageParam="truckPage"/></section>
 <section className="card fleet-team"><div className="page-header compact-header"><div><h2><ShieldCheck aria-hidden="true"/>Driver access</h2><p className="page-subtitle">Assign one truck, then choose what the driver may do.</p></div></div><div className="fleet-driver-list">{drivers.map(driver=><details className="fleet-driver-manager" key={driver.id}><summary><div className="fleet-driver-identity"><strong>{driver.name}</strong><span>{driver.assigned_vehicles||'No truck assigned'}</span><small>{driver.email}</small></div><span className="button secondary small"><UserRound aria-hidden="true"/>Manage</span></summary><form action={`/api/fleet/drivers/${driver.id}/permissions`} method="post" className="fleet-driver-permissions"><section className="fleet-management-step"><div className="workflow-step-heading"><span>1</span><UserRound aria-hidden="true"/><div><h3>Driver</h3><p>{driver.name} · {driver.phone||driver.email}</p></div></div></section><section className="fleet-management-step"><div className="workflow-step-heading"><span>2</span><Truck aria-hidden="true"/><div><h3>Assigned truck</h3><p>One current truck at a time.</p></div></div><div className="form-group"><label htmlFor={`driver-truck-${driver.id}`}><Truck aria-hidden="true"/>Truck</label><select id={`driver-truck-${driver.id}`} name="vehicleId" defaultValue={driver.assigned_vehicle_id||''}><option value="">No truck assigned</option>{allVehicles.map(vehicle=><option value={vehicle.id} key={vehicle.id}>{vehicle.platform_number} · {vehicle.make} {vehicle.model} · {vehicle.cargo_configuration||vehicle.category}</option>)}</select></div></section><section className="fleet-management-step"><div className="workflow-step-heading"><span>3</span><KeyRound aria-hidden="true"/><div><h3>Allowed work</h3><p>Duty control stays available when a truck is assigned.</p></div></div><div className="permission-toggles"><label><input type="checkbox" name="canBrowseLoadBoard" defaultChecked={Boolean(driver.can_browse_load_board)}/><span>Shipment Board</span></label><label><input type="checkbox" name="canContactBusinesses" defaultChecked={Boolean(driver.can_contact_businesses)}/><span>Call Businesses</span></label><label><input type="checkbox" name="canNegotiateLoads" defaultChecked={Boolean(driver.can_negotiate_loads)}/><span>Agree shipments</span></label><label><input type="checkbox" name="canManageCapacity" defaultChecked={Boolean(driver.can_manage_capacity)}/><span>Capacity</span></label></div></section><button className="button icon-button-label"><Save aria-hidden="true"/>Save driver</button></form></details>)}</div>{!drivers.length?<div className="empty-state">No company driver added.</div>:null}<Pagination path="/app/fleet" query={{truckPage:query.truckPage}} page={driverResult.page} pageCount={driverResult.pageCount} total={driverResult.total} pageParam="driverPage"/></section>
 </div>;
}
